# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import sdk.types as _response_types
from sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from sdk.types import (
    BerryDetail,
    BerryFirmnessDetail,
    BerryFirmnessSummary,
    BerrySummary,
    PaginatedBerryFirmnessSummaryList,
    PaginatedBerrySummaryList,
)
from sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def berry_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedBerrySummaryList:
    """Lists berries, which Pokémon can eat to restore HP or status conditions, enhance
    stats, or negate damage. Use `limit` and `offset` to select a result window, and `q`
    to filter by berry name on a local API instance.

    Berries are small fruits that can provide HP and status condition restoration, stat
    enhancement, and even damage negation when eaten by Pokémon. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Berry) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/berry/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="berry_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedBerrySummaryList"), PaginatedBerrySummaryList
    )


def berry_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedBerrySummaryList:
    """Lists berries, which Pokémon can eat to restore HP or status conditions, enhance
    stats, or negate damage. Use `limit` and `offset` to select a result window, and `q`
    to filter by berry name on a local API instance.

    Berries are small fruits that can provide HP and status condition restoration, stat
    enhancement, and even damage negation when eaten by Pokémon. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Berry) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/berry/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="berry_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedBerrySummaryList"), PaginatedBerrySummaryList
    )


async def berry_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[BerrySummary]:
    """Lists berries, which Pokémon can eat to restore HP or status conditions, enhance
    stats, or negate damage. Use `limit` and `offset` to select a result window, and `q`
    to filter by berry name on a local API instance.

    Berries are small fruits that can provide HP and status condition restoration, stat
    enhancement, and even damage negation when eaten by Pokémon. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Berry) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await berry_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[BerrySummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="berry_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerrySummaryList"),
            PaginatedBerrySummaryList,
        )


async def berry_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedBerrySummaryList, BerrySummary]]:
    _page = await berry_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[BerrySummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="berry_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerrySummaryList"),
            PaginatedBerrySummaryList,
        )


def berry_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[BerrySummary]:
    """Lists berries, which Pokémon can eat to restore HP or status conditions, enhance
    stats, or negate damage. Use `limit` and `offset` to select a result window, and `q`
    to filter by berry name on a local API instance.

    Berries are small fruits that can provide HP and status condition restoration, stat
    enhancement, and even damage negation when eaten by Pokémon. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Berry) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = berry_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[BerrySummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="berry_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerrySummaryList"),
            PaginatedBerrySummaryList,
        )


def berry_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedBerrySummaryList, BerrySummary]]:
    _page = berry_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[BerrySummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="berry_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerrySummaryList"),
            PaginatedBerrySummaryList,
        )


async def berry_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> BerryDetail:
    """Retrieves a berry and its growing properties, firmness, flavors, associated item,
    and natural gift data. Supply the berry's `id` as a string or integer to look up the
    record.

    Berries are small fruits that can provide HP and status condition restoration, stat
    enhancement, and even damage negation when eaten by Pokémon. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Berry) for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/berry/{encode_path_segment(id)}/",
        operation_id="berry_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BerryDetail"), BerryDetail
    )


def berry_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> BerryDetail:
    """Retrieves a berry and its growing properties, firmness, flavors, associated item,
    and natural gift data. Supply the berry's `id` as a string or integer to look up the
    record.

    Berries are small fruits that can provide HP and status condition restoration, stat
    enhancement, and even damage negation when eaten by Pokémon. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Berry) for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/berry/{encode_path_segment(id)}/",
        operation_id="berry_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BerryDetail"), BerryDetail
    )


async def berry_firmness_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedBerryFirmnessSummaryList:
    """Lists berry firmness categories, which describe how soft or hard berries are. Use
    `limit` and `offset` to select a result window, and `q` to filter categories by name
    on a local API instance.

    Berries can be soft or hard. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Category:Berries_by_firmness)
    for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/berry-firmness/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="berry_firmness_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedBerryFirmnessSummaryList"),
        PaginatedBerryFirmnessSummaryList,
    )


def berry_firmness_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedBerryFirmnessSummaryList:
    """Lists berry firmness categories, which describe how soft or hard berries are. Use
    `limit` and `offset` to select a result window, and `q` to filter categories by name
    on a local API instance.

    Berries can be soft or hard. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Category:Berries_by_firmness)
    for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/berry-firmness/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="berry_firmness_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedBerryFirmnessSummaryList"),
        PaginatedBerryFirmnessSummaryList,
    )


async def berry_firmness_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[BerryFirmnessSummary]:
    """Lists berry firmness categories, which describe how soft or hard berries are. Use
    `limit` and `offset` to select a result window, and `q` to filter categories by name
    on a local API instance.

    Berries can be soft or hard. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Category:Berries_by_firmness)
    for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await berry_firmness_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[BerryFirmnessSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="berry_firmness_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerryFirmnessSummaryList"),
            PaginatedBerryFirmnessSummaryList,
        )


async def berry_firmness_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedBerryFirmnessSummaryList, BerryFirmnessSummary]]:
    _page = await berry_firmness_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[BerryFirmnessSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="berry_firmness_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerryFirmnessSummaryList"),
            PaginatedBerryFirmnessSummaryList,
        )


def berry_firmness_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[BerryFirmnessSummary]:
    """Lists berry firmness categories, which describe how soft or hard berries are. Use
    `limit` and `offset` to select a result window, and `q` to filter categories by name
    on a local API instance.

    Berries can be soft or hard. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Category:Berries_by_firmness)
    for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = berry_firmness_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[BerryFirmnessSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="berry_firmness_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerryFirmnessSummaryList"),
            PaginatedBerryFirmnessSummaryList,
        )


def berry_firmness_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedBerryFirmnessSummaryList, BerryFirmnessSummary]]:
    _page = berry_firmness_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[BerryFirmnessSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="berry_firmness_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedBerryFirmnessSummaryList"),
            PaginatedBerryFirmnessSummaryList,
        )


async def berry_firmness_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> BerryFirmnessDetail:
    """Retrieves a berry firmness category and the berries assigned to it. Supply the
    category's `id` as a string or integer to look up its associated berry list and
    localized names.

    Berries can be soft or hard. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Category:Berries_by_firmness)
    for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/berry-firmness/{encode_path_segment(id)}/",
        operation_id="berry_firmness_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BerryFirmnessDetail"), BerryFirmnessDetail
    )


def berry_firmness_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> BerryFirmnessDetail:
    """Retrieves a berry firmness category and the berries assigned to it. Supply the
    category's `id` as a string or integer to look up its associated berry list and
    localized names.

    Berries can be soft or hard. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Category:Berries_by_firmness)
    for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/berry-firmness/{encode_path_segment(id)}/",
        operation_id="berry_firmness_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BerryFirmnessDetail"), BerryFirmnessDetail
    )


__all__ = [
    "berry_firmness_list",
    "berry_firmness_list_pages",
    "berry_firmness_list_pages_sync",
    "berry_firmness_list_paginated",
    "berry_firmness_list_paginated_sync",
    "berry_firmness_list_sync",
    "berry_firmness_retrieve",
    "berry_firmness_retrieve_sync",
    "berry_list",
    "berry_list_pages",
    "berry_list_pages_sync",
    "berry_list_paginated",
    "berry_list_paginated_sync",
    "berry_list_sync",
    "berry_retrieve",
    "berry_retrieve_sync",
]
