# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from octri_pokeapi_unofficial_demo_sdk.client import NOT_GIVEN, NotGiven
from octri_pokeapi_unofficial_demo_sdk.types.shared import (
    BerryFlavorSummary,
    BerrySummary,
    ContestTypeSummary,
    ItemSummary,
    LanguageSummary,
    TypeSummary,
)

from ..validation import validate_length, validate_range, validate_required, validate_uri


class BerryDetail(BaseModel):
    """Typed representation of the `BerryDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    firmness: BerryFirmnessSummary
    """Required object value serialized in the `firmness` wire field."""
    flavors: list[BerryFlavorMap]
    """Required array value serialized in the `flavors` wire field."""
    item: ItemSummary
    """Required object value serialized in the `item` wire field."""
    natural_gift_type: TypeSummary
    """Required object value serialized in the `natural_gift_type` wire field."""
    growth_time: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `growth_time` wire field."""
    max_harvest: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `max_harvest` wire field."""
    natural_gift_power: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `natural_gift_power` wire field."""
    size: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `size` wire field."""
    smoothness: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `smoothness` wire field."""
    soil_dryness: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `soil_dryness` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["firmness", "flavors", "id", "item", "name", "natural_gift_type"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("growth_time")
    @classmethod
    def _validate_growth_time(cls, value):
        if value is not None:
            validate_range("growth_time", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("max_harvest")
    @classmethod
    def _validate_max_harvest(cls, value):
        if value is not None:
            validate_range("max_harvest", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("natural_gift_power")
    @classmethod
    def _validate_natural_gift_power(cls, value):
        if value is not None:
            validate_range("natural_gift_power", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("size")
    @classmethod
    def _validate_size(cls, value):
        if value is not None:
            validate_range("size", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("smoothness")
    @classmethod
    def _validate_smoothness(cls, value):
        if value is not None:
            validate_range("smoothness", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("soil_dryness")
    @classmethod
    def _validate_soil_dryness(cls, value):
        if value is not None:
            validate_range("soil_dryness", value, min=-2147483648, max=2147483647)
        return value


class BerryFirmnessDetail(BaseModel):
    """Typed representation of the `BerryFirmnessDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    berries: list[BerrySummary]
    """Required array value serialized in the `berries` wire field."""
    names: list[BerryFirmnessName]
    """Required array value serialized in the `names` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["berries", "id", "name", "names"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class BerryFirmnessName(BaseModel):
    """Typed representation of the `BerryFirmnessName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class BerryFirmnessSummary(BaseModel):
    """Typed representation of the `BerryFirmnessSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class BerryFlavorBerryMap(BaseModel):
    """Typed representation of the `BerryFlavorBerryMap` API schema."""

    potency: int
    """Required `integer` value serialized in the `potency` wire field."""
    berry: BerrySummary
    """Required object value serialized in the `berry` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["berry", "potency"])
        return value

    @field_validator("potency")
    @classmethod
    def _validate_potency(cls, value):
        validate_range("potency", value, min=-2147483648, max=2147483647)
        return value


class BerryFlavorDetail(BaseModel):
    """Typed representation of the `BerryFlavorDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    berries: list[BerryFlavorBerryMap]
    """Required array value serialized in the `berries` wire field."""
    contest_type: ContestTypeSummary
    """Required object value serialized in the `contest_type` wire field."""
    names: list[BerryFlavorName]
    """Required array value serialized in the `names` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["berries", "contest_type", "id", "name", "names"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class BerryFlavorMap(BaseModel):
    """Typed representation of the `BerryFlavorMap` API schema."""

    potency: int
    """Required `integer` value serialized in the `potency` wire field."""
    flavor: BerryFlavorSummary
    """Required object value serialized in the `flavor` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["flavor", "potency"])
        return value

    @field_validator("potency")
    @classmethod
    def _validate_potency(cls, value):
        validate_range("potency", value, min=-2147483648, max=2147483647)
        return value


class BerryFlavorName(BaseModel):
    """Typed representation of the `BerryFlavorName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PaginatedBerryFirmnessSummaryList(BaseModel):
    """Typed representation of the `PaginatedBerryFirmnessSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[BerryFirmnessSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedBerryFlavorSummaryList(BaseModel):
    """Typed representation of the `PaginatedBerryFlavorSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[BerryFlavorSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedBerrySummaryList(BaseModel):
    """Typed representation of the `PaginatedBerrySummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[BerrySummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value
