# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

import importlib

from .evolution_part001 import (
    EvolutionChainDetail,
    EvolutionChainLink,
    EvolutionConditionExpression,
    EvolutionTriggerDetail,
    EvolutionTriggerName,
    EvolutionTriggerSummary,
    EvolutionVariableDescription,
    EvolutionVariableDetail,
    EvolutionVariableName,
    EvolutionVariableSummary,
    PaginatedEvolutionChainSummaryList,
    PaginatedEvolutionTriggerSummaryList,
    PaginatedEvolutionVariableSummaryList,
)
from .evolution_part002 import PokemonEvolution

__all__ = [
    "EvolutionChainDetail",
    "EvolutionChainLink",
    "EvolutionConditionExpression",
    "EvolutionTriggerDetail",
    "EvolutionTriggerName",
    "EvolutionTriggerSummary",
    "EvolutionVariableDescription",
    "EvolutionVariableDetail",
    "EvolutionVariableName",
    "EvolutionVariableSummary",
    "PaginatedEvolutionChainSummaryList",
    "PaginatedEvolutionTriggerSummaryList",
    "PaginatedEvolutionVariableSummaryList",
    "PokemonEvolution",
]

# Forward references deferred to TYPE_CHECKING in the parts above are
# resolvable now that every part is loaded.
_evolution_part001 = importlib.import_module(".evolution_part001", __package__)

_deferred_evolution_part001: tuple[tuple[str, object], ...] = (
    ("PokemonEvolution", PokemonEvolution),
)
for _name, _value in _deferred_evolution_part001:
    setattr(_evolution_part001, _name, _value)

EvolutionChainDetail.model_rebuild()
EvolutionChainLink.model_rebuild()
EvolutionConditionExpression.model_rebuild()
EvolutionTriggerDetail.model_rebuild()
EvolutionTriggerName.model_rebuild()
EvolutionTriggerSummary.model_rebuild()
EvolutionVariableDescription.model_rebuild()
EvolutionVariableDetail.model_rebuild()
EvolutionVariableName.model_rebuild()
EvolutionVariableSummary.model_rebuild()
PaginatedEvolutionChainSummaryList.model_rebuild()
PaginatedEvolutionTriggerSummaryList.model_rebuild()
PaginatedEvolutionVariableSummaryList.model_rebuild()
