# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from octri_pokeapi_unofficial_demo_sdk.client import NOT_GIVEN, NotGiven
from octri_pokeapi_unofficial_demo_sdk.types.shared import (
    AbilitySummary,
    GenerationSummary,
    LanguageSummary,
    MoveLearnMethodSummary,
    MoveSummary,
    PokedexSummary,
    PokemonSpeciesSummary,
    RegionSummary,
    TypeSummary,
    VersionGroupSummary,
    VersionSummary,
)

from ..validation import validate_length, validate_range, validate_required, validate_uri


class GenerationDetail(BaseModel):
    """Typed representation of the `GenerationDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    abilities: list[AbilitySummary]
    """Required array value serialized in the `abilities` wire field."""
    main_region: RegionSummary
    """Required object value serialized in the `main_region` wire field."""
    moves: list[MoveSummary]
    """Required array value serialized in the `moves` wire field."""
    names: list[GenerationName]
    """Required array value serialized in the `names` wire field."""
    pokemon_species: list[PokemonSpeciesSummary]
    """Required array value serialized in the `pokemon_species` wire field."""
    types: list[TypeSummary]
    """Required array value serialized in the `types` wire field."""
    version_groups: list[VersionGroupSummary]
    """Required array value serialized in the `version_groups` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "abilities",
                "id",
                "main_region",
                "moves",
                "name",
                "names",
                "pokemon_species",
                "types",
                "version_groups",
            ],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class GenerationName(BaseModel):
    """Typed representation of the `GenerationName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PaginatedGenerationSummaryList(BaseModel):
    """Typed representation of the `PaginatedGenerationSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[GenerationSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedPokedexSummaryList(BaseModel):
    """Typed representation of the `PaginatedPokedexSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[PokedexSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedVersionGroupSummaryList(BaseModel):
    """Typed representation of the `PaginatedVersionGroupSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[VersionGroupSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedVersionSummaryList(BaseModel):
    """Typed representation of the `PaginatedVersionSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[VersionSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PokedexDescription(BaseModel):
    """Typed representation of the `PokedexDescription` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""
    description: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `description` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language"])
        return value

    @field_validator("description")
    @classmethod
    def _validate_description(cls, value):
        validate_length("description", value, max=2000)
        return value


class PokedexDetail(BaseModel):
    """Typed representation of the `PokedexDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    descriptions: list[PokedexDescription]
    """Required array value serialized in the `descriptions` wire field."""
    names: list[PokedexName]
    """Required array value serialized in the `names` wire field."""
    pokemon_entries: list[PokemonDexNumber]
    """Required array value serialized in the `pokemon_entries` wire field."""
    region: RegionSummary
    """Required object value serialized in the `region` wire field."""
    version_groups: list[VersionGroupSummary]
    """Required array value serialized in the `version_groups` wire field."""
    is_main_series: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_main_series` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["descriptions", "id", "name", "names", "pokemon_entries", "region", "version_groups"],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PokedexName(BaseModel):
    """Typed representation of the `PokedexName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PokemonDexNumber(BaseModel):
    """Typed representation of the `PokemonDexNumber` API schema."""

    entry_number: int
    """Required `integer` value serialized in the `entry_number` wire field."""
    pokemon_species: PokemonSpeciesSummary
    """Required object value serialized in the `pokemon_species` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["entry_number", "pokemon_species"])
        return value


class VersionDetail(BaseModel):
    """
    Should have a link to Version Group info but the Circular
    dependency and compilation order fight eachother and I'm
    not sure how to add anything other than a hyperlink
    """

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    names: list[VersionName]
    """Required array value serialized in the `names` wire field."""
    version_group: VersionGroupSummary
    """Required object value serialized in the `version_group` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["id", "name", "names", "version_group"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class VersionGroupDetail(BaseModel):
    """Typed representation of the `VersionGroupDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    generation: GenerationSummary
    """Required object value serialized in the `generation` wire field."""
    move_learn_methods: list[MoveLearnMethodSummary]
    """Required array value serialized in the `move_learn_methods` wire field."""
    pokedexes: list[PokedexSummary]
    """Required array value serialized in the `pokedexes` wire field."""
    regions: list[RegionSummary]
    """Required array value serialized in the `regions` wire field."""
    versions: list[VersionSummary]
    """Required array value serialized in the `versions` wire field."""
    order: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `order` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["generation", "id", "move_learn_methods", "name", "pokedexes", "regions", "versions"],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("order")
    @classmethod
    def _validate_order(cls, value):
        if value is not None:
            validate_range("order", value, min=-2147483648, max=2147483647)
        return value


class VersionName(BaseModel):
    """Typed representation of the `VersionName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value
