# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

import importlib

from .items_part001 import (
    CurrencyDetail,
    CurrencyName,
    CurrencySummary,
    ItemAttributeDescription,
    ItemAttributeDetail,
    ItemAttributeName,
    ItemAttributeSummary,
    ItemCategoryDetail,
    ItemCategoryName,
    ItemCategorySummary,
    ItemDetail,
    ItemEffectText,
    ItemFlavorText,
    ItemFlingEffectDetail,
    ItemFlingEffectEffectText,
    ItemFlingEffectSummary,
    ItemGameIndex,
    ItemName,
)
from .items_part002 import (
    ItemPocketDetail,
    ItemPocketName,
    ItemPocketSummary,
    ItemPrice,
    ItemSprites,
    PaginatedCurrencySummaryList,
    PaginatedItemAttributeSummaryList,
    PaginatedItemCategorySummaryList,
    PaginatedItemFlingEffectSummaryList,
    PaginatedItemPocketSummaryList,
    PaginatedItemSummaryList,
)

__all__ = [
    "CurrencyDetail",
    "CurrencyName",
    "CurrencySummary",
    "ItemAttributeDescription",
    "ItemAttributeDetail",
    "ItemAttributeName",
    "ItemAttributeSummary",
    "ItemCategoryDetail",
    "ItemCategoryName",
    "ItemCategorySummary",
    "ItemDetail",
    "ItemEffectText",
    "ItemFlavorText",
    "ItemFlingEffectDetail",
    "ItemFlingEffectEffectText",
    "ItemFlingEffectSummary",
    "ItemGameIndex",
    "ItemName",
    "ItemPocketDetail",
    "ItemPocketName",
    "ItemPocketSummary",
    "ItemPrice",
    "ItemSprites",
    "PaginatedCurrencySummaryList",
    "PaginatedItemAttributeSummaryList",
    "PaginatedItemCategorySummaryList",
    "PaginatedItemFlingEffectSummaryList",
    "PaginatedItemPocketSummaryList",
    "PaginatedItemSummaryList",
]

# Forward references deferred to TYPE_CHECKING in the parts above are
# resolvable now that every part is loaded.
_items_part001 = importlib.import_module(".items_part001", __package__)

_deferred_items_part001: tuple[tuple[str, object], ...] = (
    ("ItemPocketSummary", ItemPocketSummary),
    ("ItemPrice", ItemPrice),
    ("ItemSprites", ItemSprites),
)
for _name, _value in _deferred_items_part001:
    setattr(_items_part001, _name, _value)

CurrencyDetail.model_rebuild()
CurrencyName.model_rebuild()
CurrencySummary.model_rebuild()
ItemAttributeDescription.model_rebuild()
ItemAttributeDetail.model_rebuild()
ItemAttributeName.model_rebuild()
ItemAttributeSummary.model_rebuild()
ItemCategoryDetail.model_rebuild()
ItemCategoryName.model_rebuild()
ItemCategorySummary.model_rebuild()
ItemDetail.model_rebuild()
ItemEffectText.model_rebuild()
ItemFlavorText.model_rebuild()
ItemFlingEffectDetail.model_rebuild()
ItemFlingEffectEffectText.model_rebuild()
ItemFlingEffectSummary.model_rebuild()
ItemGameIndex.model_rebuild()
ItemName.model_rebuild()
