# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from octri_pokeapi_unofficial_demo_sdk.client import NOT_GIVEN, NotGiven
from octri_pokeapi_unofficial_demo_sdk.types.shared import (
    GenerationSummary,
    LanguageSummary,
    LocationSummary,
    PokedexSummary,
    PokemonSpeciesSummary,
    VersionGroupSummary,
)

from ..validation import validate_length, validate_range, validate_required


class PalParkAreaName(BaseModel):
    """Typed representation of the `PalParkAreaName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PalParkEncounter(BaseModel):
    """Typed representation of the `PalParkEncounter` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    rate: int
    """Required `integer` value serialized in the `rate` wire field."""
    pokemon_species: PokemonSpeciesSummary
    """Required object value serialized in the `pokemon_species` wire field."""
    base_score: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `base_score` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["pokemon_species", "rate"])
        return value

    @field_validator("base_score")
    @classmethod
    def _validate_base_score(cls, value):
        if value is not None:
            validate_range("base_score", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("rate")
    @classmethod
    def _validate_rate(cls, value):
        validate_range("rate", value, min=-2147483648, max=2147483647)
        return value


class RegionDetail(BaseModel):
    """Typed representation of the `RegionDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    locations: list[LocationSummary]
    """Required array value serialized in the `locations` wire field."""
    main_generation: GenerationSummary | None
    """Required API value serialized in the `main_generation` wire field."""
    names: list[RegionName]
    """Required array value serialized in the `names` wire field."""
    pokedexes: list[PokedexSummary]
    """Required array value serialized in the `pokedexes` wire field."""
    version_groups: list[VersionGroupSummary]
    """Required array value serialized in the `version_groups` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["id", "locations", "main_generation", "name", "names", "pokedexes", "version_groups"],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class RegionName(BaseModel):
    """Typed representation of the `RegionName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value
