# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from octri_pokeapi_unofficial_demo_sdk.client import NOT_GIVEN, NotGiven
from octri_pokeapi_unofficial_demo_sdk.types.shared import (
    EncounterConditionValueSummary,
    EncounterMethodSummary,
    GenerationSummary,
    LanguageSummary,
    LocationAreaSummary,
    LocationSummary,
    PalParkAreaSummary,
    PokemonSummary,
    RegionSummary,
    VersionSummary,
)

from ..validation import validate_length, validate_range, validate_required, validate_uri

if TYPE_CHECKING:
    from octri_pokeapi_unofficial_demo_sdk.types.location_part002 import (
        PalParkAreaName,
        PalParkEncounter,
    )


class EncounterPokemonDetail(BaseModel):
    """Typed representation of the `EncounterPokemonDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    min_perfect_ivs: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_perfect_ivs` wire field."""
    always_shiny: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `always_shiny` wire field."""
    never_shiny: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `never_shiny` wire field."""
    is_alpha: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_alpha` wire field."""

    @field_validator("min_perfect_ivs")
    @classmethod
    def _validate_min_perfect_ivs(cls, value):
        if value is not None:
            validate_range("min_perfect_ivs", value, min=-2147483648, max=2147483647)
        return value


class LocationAreaDetail(BaseModel):
    """Typed representation of the `LocationAreaDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    game_index: int
    """Required `integer` value serialized in the `game_index` wire field."""
    encounter_method_rates: list[LocationAreaEncounterRate]
    """Required array value serialized in the `encounter_method_rates` wire field."""
    location: LocationSummary
    """Required object value serialized in the `location` wire field."""
    names: list[LocationAreaName]
    """Required array value serialized in the `names` wire field."""
    pokemon_encounters: list[LocationAreaPokemonEncounter]
    """Required array value serialized in the `pokemon_encounters` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "encounter_method_rates",
                "game_index",
                "id",
                "location",
                "name",
                "names",
                "pokemon_encounters",
            ],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("game_index")
    @classmethod
    def _validate_game_index(cls, value):
        validate_range("game_index", value, min=-2147483648, max=2147483647)
        return value


class LocationAreaEncounterDetail(BaseModel):
    """Typed representation of the `LocationAreaEncounterDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    min_level: int
    """Required `integer` value serialized in the `min_level` wire field."""
    max_level: int
    """Required `integer` value serialized in the `max_level` wire field."""
    condition_values: list[EncounterConditionValueSummary]
    """Required array value serialized in the `condition_values` wire field."""
    pokemon_details: EncounterPokemonDetail | None
    """Required API value serialized in the `pokemon_details` wire field."""
    chance: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `chance` wire field."""
    method: EncounterMethodSummary | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `method` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["condition_values", "max_level", "min_level", "pokemon_details"])
        return value


class LocationAreaEncounterRate(BaseModel):
    """Typed representation of the `LocationAreaEncounterRate` API schema."""

    encounter_method: EncounterMethodSummary
    """Required object value serialized in the `encounter_method` wire field."""
    version_details: list[LocationAreaEncounterVersionDetail]
    """Required array value serialized in the `version_details` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["encounter_method", "version_details"])
        return value


class LocationAreaEncounterVersionDetail(BaseModel):
    """Typed representation of the `LocationAreaEncounterVersionDetail` API schema."""

    rate: int
    """Required `integer` value serialized in the `rate` wire field."""
    version: VersionSummary
    """Required object value serialized in the `version` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["rate", "version"])
        return value


class LocationAreaName(BaseModel):
    """Typed representation of the `LocationAreaName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class LocationAreaPokemonEncounter(BaseModel):
    """Typed representation of the `LocationAreaPokemonEncounter` API schema."""

    pokemon: PokemonSummary
    """Required object value serialized in the `pokemon` wire field."""
    version_details: list[LocationAreaPokemonEncounterVersion]
    """Required array value serialized in the `version_details` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["pokemon", "version_details"])
        return value


class LocationAreaPokemonEncounterVersion(BaseModel):
    """Typed representation of the `LocationAreaPokemonEncounterVersion` API schema."""

    version: VersionSummary
    """Required object value serialized in the `version` wire field."""
    max_chance: int
    """Required `integer` value serialized in the `max_chance` wire field."""
    encounter_details: list[LocationAreaEncounterDetail]
    """Required array value serialized in the `encounter_details` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["encounter_details", "max_chance", "version"])
        return value


class LocationDetail(BaseModel):
    """Typed representation of the `LocationDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    region: RegionSummary | None
    """Required API value serialized in the `region` wire field."""
    names: list[LocationName]
    """Required array value serialized in the `names` wire field."""
    game_indices: list[LocationGameIndex]
    """Required array value serialized in the `game_indices` wire field."""
    areas: list[LocationAreaSummary]
    """Required array value serialized in the `areas` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["areas", "game_indices", "id", "name", "names", "region"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class LocationGameIndex(BaseModel):
    """Typed representation of the `LocationGameIndex` API schema."""

    game_index: int
    """Required `integer` value serialized in the `game_index` wire field."""
    generation: GenerationSummary
    """Required object value serialized in the `generation` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["game_index", "generation"])
        return value

    @field_validator("game_index")
    @classmethod
    def _validate_game_index(cls, value):
        validate_range("game_index", value, min=-2147483648, max=2147483647)
        return value


class LocationName(BaseModel):
    """Typed representation of the `LocationName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PaginatedLocationAreaSummaryList(BaseModel):
    """Typed representation of the `PaginatedLocationAreaSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[LocationAreaSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedLocationSummaryList(BaseModel):
    """Typed representation of the `PaginatedLocationSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[LocationSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedPalParkAreaSummaryList(BaseModel):
    """Typed representation of the `PaginatedPalParkAreaSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[PalParkAreaSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedRegionSummaryList(BaseModel):
    """Typed representation of the `PaginatedRegionSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[RegionSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PalParkAreaDetail(BaseModel):
    """Typed representation of the `PalParkAreaDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    names: list[PalParkAreaName]
    """Required array value serialized in the `names` wire field."""
    pokemon_encounters: list[PalParkEncounter]
    """Required array value serialized in the `pokemon_encounters` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["id", "name", "names", "pokemon_encounters"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value
