# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

import importlib

from .moves_part001 import (
    MoveBattleStyleDetail,
    MoveBattleStyleName,
    MoveChange,
    MoveCombos,
    MoveComboUsage,
    MoveDetail,
    MoveEffectChange,
    MoveEffectChangeEffectText,
    MoveEffectEffectText,
    MoveFlavorText,
    MoveLearnMethodDescription,
    MoveLearnMethodDetail,
    MoveLearnMethodName,
    MoveMeta,
)
from .moves_part002 import (
    MoveMetaAilmentDetail,
    MoveMetaAilmentName,
    MoveMetaAilmentSummary,
    MoveMetaCategoryDescription,
    MoveMetaCategoryDetail,
    MoveMetaCategorySummary,
    MoveMetaStatChange,
    MoveName,
    MoveTargetDescription,
    MoveTargetDetail,
    MoveTargetName,
    MoveTargetSummary,
    PaginatedMoveBattleStyleSummaryList,
    PaginatedMoveLearnMethodSummaryList,
    PaginatedMoveMetaAilmentSummaryList,
)
from .moves_part003 import (
    PaginatedMoveMetaCategorySummaryList,
    PaginatedMoveSummaryList,
    PaginatedMoveTargetSummaryList,
)

__all__ = [
    "MoveBattleStyleDetail",
    "MoveBattleStyleName",
    "MoveChange",
    "MoveComboUsage",
    "MoveCombos",
    "MoveDetail",
    "MoveEffectChange",
    "MoveEffectChangeEffectText",
    "MoveEffectEffectText",
    "MoveFlavorText",
    "MoveLearnMethodDescription",
    "MoveLearnMethodDetail",
    "MoveLearnMethodName",
    "MoveMeta",
    "MoveMetaAilmentDetail",
    "MoveMetaAilmentName",
    "MoveMetaAilmentSummary",
    "MoveMetaCategoryDescription",
    "MoveMetaCategoryDetail",
    "MoveMetaCategorySummary",
    "MoveMetaStatChange",
    "MoveName",
    "MoveTargetDescription",
    "MoveTargetDetail",
    "MoveTargetName",
    "MoveTargetSummary",
    "PaginatedMoveBattleStyleSummaryList",
    "PaginatedMoveLearnMethodSummaryList",
    "PaginatedMoveMetaAilmentSummaryList",
    "PaginatedMoveMetaCategorySummaryList",
    "PaginatedMoveSummaryList",
    "PaginatedMoveTargetSummaryList",
]

# Forward references deferred to TYPE_CHECKING in the parts above are
# resolvable now that every part is loaded.
_moves_part001 = importlib.import_module(".moves_part001", __package__)

_deferred_moves_part001: tuple[tuple[str, object], ...] = (
    ("MoveMetaAilmentSummary", MoveMetaAilmentSummary),
    ("MoveMetaCategorySummary", MoveMetaCategorySummary),
    ("MoveMetaStatChange", MoveMetaStatChange),
    ("MoveName", MoveName),
    ("MoveTargetSummary", MoveTargetSummary),
)
for _name, _value in _deferred_moves_part001:
    setattr(_moves_part001, _name, _value)

MoveBattleStyleDetail.model_rebuild()
MoveBattleStyleName.model_rebuild()
MoveChange.model_rebuild()
MoveComboUsage.model_rebuild()
MoveCombos.model_rebuild()
MoveDetail.model_rebuild()
MoveEffectChange.model_rebuild()
MoveEffectChangeEffectText.model_rebuild()
MoveEffectEffectText.model_rebuild()
MoveFlavorText.model_rebuild()
MoveLearnMethodDescription.model_rebuild()
MoveLearnMethodDetail.model_rebuild()
MoveLearnMethodName.model_rebuild()
MoveMeta.model_rebuild()
