# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

import importlib

from .pokemon_pokemon_part001 import (
    PokemonAbility,
    PokemonAbilityPast,
    PokemonColorDetail,
    PokemonColorName,
    PokemonColorSummary,
    PokemonCries,
    PokemonDetail,
    PokemonDexEntry,
    PokemonFormDetail,
    PokemonFormFlavorText,
    PokemonFormName,
    PokemonFormSprites,
    PokemonFormTriggerCondition,
    PokemonFormType,
    PokemonGameIndex,
    PokemonHabitatDetail,
    PokemonHabitatName,
)
from .pokemon_pokemon_part002 import (
    PokemonHabitatSummary,
    PokemonMove,
    PokemonMoveVersionGroup,
    PokemonPastAbility,
    PokemonPastStat,
    PokemonPastType,
    PokemonShapeAwesomeName,
    PokemonShapeDetail,
    PokemonShapeName,
    PokemonShapeSummary,
    PokemonSpeciesDescription,
    PokemonSpeciesDetail,
    PokemonSpeciesFlavorText,
    PokemonSpeciesGenus,
    PokemonSpeciesName,
    PokemonSpeciesPalParkEncounter,
    PokemonSpeciesVariety,
    PokemonSprites,
)
from .pokemon_pokemon_part003 import PokemonStat, PokemonType

__all__ = [
    "PokemonAbility",
    "PokemonAbilityPast",
    "PokemonColorDetail",
    "PokemonColorName",
    "PokemonColorSummary",
    "PokemonCries",
    "PokemonDetail",
    "PokemonDexEntry",
    "PokemonFormDetail",
    "PokemonFormFlavorText",
    "PokemonFormName",
    "PokemonFormSprites",
    "PokemonFormTriggerCondition",
    "PokemonFormType",
    "PokemonGameIndex",
    "PokemonHabitatDetail",
    "PokemonHabitatName",
    "PokemonHabitatSummary",
    "PokemonMove",
    "PokemonMoveVersionGroup",
    "PokemonPastAbility",
    "PokemonPastStat",
    "PokemonPastType",
    "PokemonShapeAwesomeName",
    "PokemonShapeDetail",
    "PokemonShapeName",
    "PokemonShapeSummary",
    "PokemonSpeciesDescription",
    "PokemonSpeciesDetail",
    "PokemonSpeciesFlavorText",
    "PokemonSpeciesGenus",
    "PokemonSpeciesName",
    "PokemonSpeciesPalParkEncounter",
    "PokemonSpeciesVariety",
    "PokemonSprites",
    "PokemonStat",
    "PokemonType",
]

# Forward references deferred to TYPE_CHECKING in the parts above are
# resolvable now that every part is loaded.
_pokemon_pokemon_part001 = importlib.import_module(".pokemon_pokemon_part001", __package__)

_deferred_pokemon_pokemon_part001: tuple[tuple[str, object], ...] = (
    ("PokemonMove", PokemonMove),
    ("PokemonPastAbility", PokemonPastAbility),
    ("PokemonPastStat", PokemonPastStat),
    ("PokemonPastType", PokemonPastType),
    ("PokemonSprites", PokemonSprites),
    ("PokemonStat", PokemonStat),
    ("PokemonType", PokemonType),
)
for _name, _value in _deferred_pokemon_pokemon_part001:
    setattr(_pokemon_pokemon_part001, _name, _value)

PokemonAbility.model_rebuild()
PokemonAbilityPast.model_rebuild()
PokemonColorDetail.model_rebuild()
PokemonColorName.model_rebuild()
PokemonColorSummary.model_rebuild()
PokemonCries.model_rebuild()
PokemonDetail.model_rebuild()
PokemonDexEntry.model_rebuild()
PokemonFormDetail.model_rebuild()
PokemonFormFlavorText.model_rebuild()
PokemonFormName.model_rebuild()
PokemonFormSprites.model_rebuild()
PokemonFormTriggerCondition.model_rebuild()
PokemonFormType.model_rebuild()
PokemonGameIndex.model_rebuild()
PokemonHabitatDetail.model_rebuild()
PokemonHabitatName.model_rebuild()

_pokemon_pokemon_part002 = importlib.import_module(".pokemon_pokemon_part002", __package__)

_deferred_pokemon_pokemon_part002: tuple[tuple[str, object], ...] = (("PokemonStat", PokemonStat),)
for _name, _value in _deferred_pokemon_pokemon_part002:
    setattr(_pokemon_pokemon_part002, _name, _value)

PokemonHabitatSummary.model_rebuild()
PokemonMove.model_rebuild()
PokemonMoveVersionGroup.model_rebuild()
PokemonPastAbility.model_rebuild()
PokemonPastStat.model_rebuild()
PokemonPastType.model_rebuild()
PokemonShapeAwesomeName.model_rebuild()
PokemonShapeDetail.model_rebuild()
PokemonShapeName.model_rebuild()
PokemonShapeSummary.model_rebuild()
PokemonSpeciesDescription.model_rebuild()
PokemonSpeciesDetail.model_rebuild()
PokemonSpeciesFlavorText.model_rebuild()
PokemonSpeciesGenus.model_rebuild()
PokemonSpeciesName.model_rebuild()
PokemonSpeciesPalParkEncounter.model_rebuild()
PokemonSpeciesVariety.model_rebuild()
PokemonSprites.model_rebuild()
