# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from octri_pokeapi_unofficial_demo_sdk.client import NOT_GIVEN, NotGiven
from octri_pokeapi_unofficial_demo_sdk.types.shared import (
    GenerationSummary,
    LanguageSummary,
    PokemonSummary,
    VersionGroupSummary,
)

from ..validation import validate_length, validate_range, validate_required


class AbilityChange(BaseModel):
    """Typed representation of the `AbilityChange` API schema."""

    version_group: VersionGroupSummary
    """Required object value serialized in the `version_group` wire field."""
    effect_entries: list[AbilityChangeEffectText]
    """Required array value serialized in the `effect_entries` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["effect_entries", "version_group"])
        return value


class AbilityChangeEffectText(BaseModel):
    """Typed representation of the `AbilityChangeEffectText` API schema."""

    effect: str
    """Required `string` value serialized in the `effect` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["effect", "language"])
        return value

    @field_validator("effect")
    @classmethod
    def _validate_effect(cls, value):
        validate_length("effect", value, max=6000)
        return value


class AbilityDetail(BaseModel):
    """Typed representation of the `AbilityDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    generation: GenerationSummary
    """Required object value serialized in the `generation` wire field."""
    names: list[AbilityName]
    """Required array value serialized in the `names` wire field."""
    effect_entries: list[AbilityEffectText]
    """Required array value serialized in the `effect_entries` wire field."""
    effect_changes: list[AbilityChange]
    """Required array value serialized in the `effect_changes` wire field."""
    flavor_text_entries: list[AbilityFlavorText]
    """Required array value serialized in the `flavor_text_entries` wire field."""
    pokemon: list[AbilityPokemonDetail]
    """Required array value serialized in the `pokemon` wire field."""
    is_main_series: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_main_series` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "effect_changes",
                "effect_entries",
                "flavor_text_entries",
                "generation",
                "id",
                "name",
                "names",
                "pokemon",
            ],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class AbilityEffectText(BaseModel):
    """Typed representation of the `AbilityEffectText` API schema."""

    effect: str
    """Required `string` value serialized in the `effect` wire field."""
    short_effect: str
    """Required `string` value serialized in the `short_effect` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["effect", "language", "short_effect"])
        return value

    @field_validator("effect")
    @classmethod
    def _validate_effect(cls, value):
        validate_length("effect", value, max=6000)
        return value

    @field_validator("short_effect")
    @classmethod
    def _validate_short_effect(cls, value):
        validate_length("short_effect", value, max=300)
        return value


class AbilityFlavorText(BaseModel):
    """Typed representation of the `AbilityFlavorText` API schema."""

    flavor_text: str
    """Required `string` value serialized in the `flavor_text` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""
    version_group: VersionGroupSummary
    """Required object value serialized in the `version_group` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["flavor_text", "language", "version_group"])
        return value


class AbilityName(BaseModel):
    """Typed representation of the `AbilityName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class AbilityPokemonDetail(BaseModel):
    """Typed representation of the `AbilityPokemonDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    slot: int
    """Required `integer` value serialized in the `slot` wire field."""
    pokemon: PokemonSummary
    """Required object value serialized in the `pokemon` wire field."""
    is_hidden: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_hidden` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["pokemon", "slot"])
        return value

    @field_validator("slot")
    @classmethod
    def _validate_slot(cls, value):
        validate_range("slot", value, min=-2147483648, max=2147483647)
        return value
