# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from octri_pokeapi_unofficial_demo_sdk.client import NOT_GIVEN, NotGiven
from octri_pokeapi_unofficial_demo_sdk.types.pokemon_egg import EggGroupSummary
from octri_pokeapi_unofficial_demo_sdk.types.pokemon_growth import GrowthRateSummary
from octri_pokeapi_unofficial_demo_sdk.types.pokemon_pokemon_part001 import (
    PokemonAbilityPast,
    PokemonColorSummary,
    PokemonDexEntry,
)
from octri_pokeapi_unofficial_demo_sdk.types.pokemon_type import TypePokemon
from octri_pokeapi_unofficial_demo_sdk.types.shared import (
    EvolutionChainSummary,
    GenerationSummary,
    LanguageSummary,
    MoveLearnMethodSummary,
    MoveSummary,
    PalParkAreaSummary,
    PokemonSpeciesSummary,
    PokemonSummary,
    VersionGroupSummary,
    VersionSummary,
)

from ..validation import validate_length, validate_range, validate_required, validate_uri

if TYPE_CHECKING:
    from octri_pokeapi_unofficial_demo_sdk.types.pokemon_pokemon_part003 import PokemonStat


class PokemonHabitatSummary(BaseModel):
    """Typed representation of the `PokemonHabitatSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PokemonMove(BaseModel):
    """Typed representation of the `PokemonMove` API schema."""

    move: MoveSummary
    """Required object value serialized in the `move` wire field."""
    version_group_details: list[PokemonMoveVersionGroup]
    """Required array value serialized in the `version_group_details` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["move", "version_group_details"])
        return value


class PokemonMoveVersionGroup(BaseModel):
    """Typed representation of the `PokemonMoveVersionGroup` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    level_learned_at: int
    """Required `integer` value serialized in the `level_learned_at` wire field."""
    move_learn_method: MoveLearnMethodSummary
    """Required object value serialized in the `move_learn_method` wire field."""
    version_group: VersionGroupSummary
    """Required object value serialized in the `version_group` wire field."""
    order: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `order` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["level_learned_at", "move_learn_method", "version_group"])
        return value


class PokemonPastAbility(BaseModel):
    """Typed representation of the `PokemonPastAbility` API schema."""

    abilities: list[PokemonAbilityPast]
    """Required array value serialized in the `abilities` wire field."""
    generation: GenerationSummary
    """Required object value serialized in the `generation` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["abilities", "generation"])
        return value


class PokemonPastStat(BaseModel):
    """Typed representation of the `PokemonPastStat` API schema."""

    generation: GenerationSummary
    """Required object value serialized in the `generation` wire field."""
    stats: list[PokemonStat]
    """Required array value serialized in the `stats` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["generation", "stats"])
        return value


class PokemonPastType(BaseModel):
    """Typed representation of the `PokemonPastType` API schema."""

    generation: GenerationSummary
    """Required object value serialized in the `generation` wire field."""
    types: list[TypePokemon]
    """Required array value serialized in the `types` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["generation", "types"])
        return value


class PokemonShapeAwesomeName(BaseModel):
    """Typed representation of the `PokemonShapeAwesomeName` API schema."""

    awesome_name: str
    """Required `string` value serialized in the `awesome_name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["awesome_name", "language"])
        return value

    @field_validator("awesome_name")
    @classmethod
    def _validate_awesome_name(cls, value):
        validate_length("awesome_name", value, max=30)
        return value


class PokemonShapeDetail(BaseModel):
    """Typed representation of the `PokemonShapeDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    awesome_names: list[PokemonShapeAwesomeName]
    """Required array value serialized in the `awesome_names` wire field."""
    names: list[PokemonShapeName]
    """Required array value serialized in the `names` wire field."""
    pokemon_species: list[PokemonSpeciesSummary]
    """Required array value serialized in the `pokemon_species` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["awesome_names", "id", "name", "names", "pokemon_species"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PokemonShapeName(BaseModel):
    """Typed representation of the `PokemonShapeName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PokemonShapeSummary(BaseModel):
    """Typed representation of the `PokemonShapeSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PokemonSpeciesDescription(BaseModel):
    """Typed representation of the `PokemonSpeciesDescription` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""
    description: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `description` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language"])
        return value

    @field_validator("description")
    @classmethod
    def _validate_description(cls, value):
        validate_length("description", value, max=2000)
        return value


class PokemonSpeciesDetail(BaseModel):
    """Typed representation of the `PokemonSpeciesDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    growth_rate: GrowthRateSummary
    """Required object value serialized in the `growth_rate` wire field."""
    pokedex_numbers: list[PokemonDexEntry]
    """Required array value serialized in the `pokedex_numbers` wire field."""
    egg_groups: list[EggGroupSummary]
    """Required array value serialized in the `egg_groups` wire field."""
    color: PokemonColorSummary
    """Required object value serialized in the `color` wire field."""
    shape: PokemonShapeSummary
    """Required object value serialized in the `shape` wire field."""
    evolves_from_species: PokemonSpeciesSummary
    """Required object value serialized in the `evolves_from_species` wire field."""
    evolution_chain: EvolutionChainSummary
    """Required object value serialized in the `evolution_chain` wire field."""
    habitat: PokemonHabitatSummary
    """Required object value serialized in the `habitat` wire field."""
    generation: GenerationSummary
    """Required object value serialized in the `generation` wire field."""
    names: list[PokemonSpeciesName]
    """Required array value serialized in the `names` wire field."""
    pal_park_encounters: list[PokemonSpeciesPalParkEncounter]
    """Required array value serialized in the `pal_park_encounters` wire field."""
    form_descriptions: list[PokemonSpeciesDescription]
    """Required array value serialized in the `form_descriptions` wire field."""
    flavor_text_entries: list[PokemonSpeciesFlavorText]
    """Required array value serialized in the `flavor_text_entries` wire field."""
    genera: list[PokemonSpeciesGenus]
    """Required array value serialized in the `genera` wire field."""
    varieties: list[PokemonSpeciesVariety]
    """Required array value serialized in the `varieties` wire field."""
    order: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `order` wire field."""
    gender_rate: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `gender_rate` wire field."""
    capture_rate: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `capture_rate` wire field."""
    base_happiness: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `base_happiness` wire field."""
    is_baby: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_baby` wire field."""
    is_legendary: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_legendary` wire field."""
    is_mythical: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_mythical` wire field."""
    hatch_counter: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `hatch_counter` wire field."""
    has_gender_differences: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `has_gender_differences` wire field."""
    forms_switchable: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `forms_switchable` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "color",
                "egg_groups",
                "evolution_chain",
                "evolves_from_species",
                "flavor_text_entries",
                "form_descriptions",
                "genera",
                "generation",
                "growth_rate",
                "habitat",
                "id",
                "name",
                "names",
                "pal_park_encounters",
                "pokedex_numbers",
                "shape",
                "varieties",
            ],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("order")
    @classmethod
    def _validate_order(cls, value):
        if value is not None:
            validate_range("order", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("gender_rate")
    @classmethod
    def _validate_gender_rate(cls, value):
        if value is not None:
            validate_range("gender_rate", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("capture_rate")
    @classmethod
    def _validate_capture_rate(cls, value):
        if value is not None:
            validate_range("capture_rate", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("base_happiness")
    @classmethod
    def _validate_base_happiness(cls, value):
        if value is not None:
            validate_range("base_happiness", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("hatch_counter")
    @classmethod
    def _validate_hatch_counter(cls, value):
        if value is not None:
            validate_range("hatch_counter", value, min=-2147483648, max=2147483647)
        return value


class PokemonSpeciesFlavorText(BaseModel):
    """Typed representation of the `PokemonSpeciesFlavorText` API schema."""

    flavor_text: str
    """Required `string` value serialized in the `flavor_text` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""
    version: VersionSummary
    """Required object value serialized in the `version` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["flavor_text", "language", "version"])
        return value


class PokemonSpeciesGenus(BaseModel):
    """Typed representation of the `PokemonSpeciesGenus` API schema."""

    genus: str
    """Required `string` value serialized in the `genus` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["genus", "language"])
        return value

    @field_validator("genus")
    @classmethod
    def _validate_genus(cls, value):
        validate_length("genus", value, max=30)
        return value


class PokemonSpeciesName(BaseModel):
    """Typed representation of the `PokemonSpeciesName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PokemonSpeciesPalParkEncounter(BaseModel):
    """Typed representation of the `PokemonSpeciesPalParkEncounter` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    rate: int
    """Required `integer` value serialized in the `rate` wire field."""
    area: PalParkAreaSummary
    """Required object value serialized in the `area` wire field."""
    base_score: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `base_score` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["area", "rate"])
        return value

    @field_validator("base_score")
    @classmethod
    def _validate_base_score(cls, value):
        if value is not None:
            validate_range("base_score", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("rate")
    @classmethod
    def _validate_rate(cls, value):
        validate_range("rate", value, min=-2147483648, max=2147483647)
        return value


class PokemonSpeciesVariety(BaseModel):
    """Typed representation of the `PokemonSpeciesVariety` API schema."""

    is_default: bool
    """Required `boolean` value serialized in the `is_default` wire field."""
    pokemon: PokemonSummary
    """Required object value serialized in the `pokemon` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["is_default", "pokemon"])
        return value


class PokemonSprites(BaseModel):
    """Typed representation of the `PokemonSprites` API schema."""

    front_default: str | None
    """Required `string` value serialized in the `front_default` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["front_default"])
        return value
