# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, field_validator, model_validator

from ..validation import validate_length, validate_required, validate_uri


class NatureSummary(BaseModel):
    """Typed representation of the `NatureSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PalParkAreaSummary(BaseModel):
    """Typed representation of the `PalParkAreaSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PokedexSummary(BaseModel):
    """Typed representation of the `PokedexSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PokemonFormSummary(BaseModel):
    """Typed representation of the `PokemonFormSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PokemonHeldItem(BaseModel):
    """Typed representation of the `PokemonHeldItem` API schema."""

    pokemon: PokemonSummary
    """Required object value serialized in the `pokemon` wire field."""
    version_details: list[PokemonHeldItemVersion]
    """Required array value serialized in the `version_details` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["pokemon", "version_details"])
        return value


class PokemonHeldItemVersion(BaseModel):
    """Typed representation of the `PokemonHeldItemVersion` API schema."""

    rarity: int
    """Required `integer` value serialized in the `rarity` wire field."""
    version: VersionSummary
    """Required object value serialized in the `version` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["rarity", "version"])
        return value


class PokemonSpeciesSummary(BaseModel):
    """Typed representation of the `PokemonSpeciesSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PokemonSummary(BaseModel):
    """Typed representation of the `PokemonSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class RegionSummary(BaseModel):
    """Typed representation of the `RegionSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class StatSummary(BaseModel):
    """Typed representation of the `StatSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class SuperContestEffectSummary(BaseModel):
    """Typed representation of the `SuperContestEffectSummary` API schema."""

    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["url"])
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class TypeSummary(BaseModel):
    """Typed representation of the `TypeSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class VersionGroupSummary(BaseModel):
    """Typed representation of the `VersionGroupSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class VersionSummary(BaseModel):
    """Typed representation of the `VersionSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value
