# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    EvolutionVariableDetail,
    EvolutionVariableSummary,
    PaginatedEvolutionVariableSummaryList,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def evolution_variable_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedEvolutionVariableSummaryList:
    """Lists variables used in boolean expressions for form-branching evolutions, such as
    Encryption Constant and Personality Value. Use `limit` and `offset` to control the
    result page, or search variable names with `q`, which is available only on local
    deployments.

    Evolution variables represent parameters (such as Encryption Constant and
    Personality Value) used in boolean expressions for form-branching evolutions. Check
    out [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Personality_value) for
    greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/evolution-variable/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="evolution_variable_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedEvolutionVariableSummaryList"),
        PaginatedEvolutionVariableSummaryList,
    )


def evolution_variable_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedEvolutionVariableSummaryList:
    """Lists variables used in boolean expressions for form-branching evolutions, such as
    Encryption Constant and Personality Value. Use `limit` and `offset` to control the
    result page, or search variable names with `q`, which is available only on local
    deployments.

    Evolution variables represent parameters (such as Encryption Constant and
    Personality Value) used in boolean expressions for form-branching evolutions. Check
    out [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Personality_value) for
    greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/evolution-variable/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="evolution_variable_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedEvolutionVariableSummaryList"),
        PaginatedEvolutionVariableSummaryList,
    )


async def evolution_variable_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[EvolutionVariableSummary]:
    """Lists variables used in boolean expressions for form-branching evolutions, such as
    Encryption Constant and Personality Value. Use `limit` and `offset` to control the
    result page, or search variable names with `q`, which is available only on local
    deployments.

    Evolution variables represent parameters (such as Encryption Constant and
    Personality Value) used in boolean expressions for form-branching evolutions. Check
    out [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Personality_value) for
    greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await evolution_variable_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[EvolutionVariableSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="evolution_variable_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedEvolutionVariableSummaryList"),
            PaginatedEvolutionVariableSummaryList,
        )


async def evolution_variable_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedEvolutionVariableSummaryList, EvolutionVariableSummary]]:
    _page = await evolution_variable_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[EvolutionVariableSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="evolution_variable_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedEvolutionVariableSummaryList"),
            PaginatedEvolutionVariableSummaryList,
        )


def evolution_variable_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[EvolutionVariableSummary]:
    """Lists variables used in boolean expressions for form-branching evolutions, such as
    Encryption Constant and Personality Value. Use `limit` and `offset` to control the
    result page, or search variable names with `q`, which is available only on local
    deployments.

    Evolution variables represent parameters (such as Encryption Constant and
    Personality Value) used in boolean expressions for form-branching evolutions. Check
    out [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Personality_value) for
    greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = evolution_variable_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[EvolutionVariableSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="evolution_variable_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedEvolutionVariableSummaryList"),
            PaginatedEvolutionVariableSummaryList,
        )


def evolution_variable_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedEvolutionVariableSummaryList, EvolutionVariableSummary]]:
    _page = evolution_variable_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[EvolutionVariableSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="evolution_variable_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedEvolutionVariableSummaryList"),
            PaginatedEvolutionVariableSummaryList,
        )


async def evolution_variable_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> EvolutionVariableDetail:
    """Retrieves a specific evolution variable used in boolean expressions for
    form-branching evolutions. Use `id` to retrieve its symbol, data type, source,
    version group, localized names, and descriptions.

    Evolution variables represent parameters (such as Encryption Constant and
    Personality Value) used in boolean expressions for form-branching evolutions. Check
    out [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Personality_value) for
    greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/evolution-variable/{encode_path_segment(id)}/",
        operation_id="evolution_variable_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "EvolutionVariableDetail"), EvolutionVariableDetail
    )


def evolution_variable_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> EvolutionVariableDetail:
    """Retrieves a specific evolution variable used in boolean expressions for
    form-branching evolutions. Use `id` to retrieve its symbol, data type, source,
    version group, localized names, and descriptions.

    Evolution variables represent parameters (such as Encryption Constant and
    Personality Value) used in boolean expressions for form-branching evolutions. Check
    out [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Personality_value) for
    greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/evolution-variable/{encode_path_segment(id)}/",
        operation_id="evolution_variable_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "EvolutionVariableDetail"), EvolutionVariableDetail
    )


__all__ = [
    "evolution_variable_list",
    "evolution_variable_list_pages",
    "evolution_variable_list_pages_sync",
    "evolution_variable_list_paginated",
    "evolution_variable_list_paginated_sync",
    "evolution_variable_list_sync",
    "evolution_variable_retrieve",
    "evolution_variable_retrieve_sync",
]
