# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import sdk.types as _response_types
from sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from sdk.types import MachineDetail, MachineSummary, PaginatedMachineSummaryList
from sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def machine_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedMachineSummaryList:
    """Lists machines, which represent items that teach moves to Pokémon. Use `limit` and
    `offset` to control the results page; `q` filters names case-insensitively and is
    available only in local deployments.

    Machines are the representation of items that teach moves to Pokémon. They vary from
    version to version, so it is not certain that one specific TM or HM corresponds to a
    single Machine.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/machine/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="machine_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedMachineSummaryList"),
        PaginatedMachineSummaryList,
    )


def machine_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedMachineSummaryList:
    """Lists machines, which represent items that teach moves to Pokémon. Use `limit` and
    `offset` to control the results page; `q` filters names case-insensitively and is
    available only in local deployments.

    Machines are the representation of items that teach moves to Pokémon. They vary from
    version to version, so it is not certain that one specific TM or HM corresponds to a
    single Machine.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/machine/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="machine_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedMachineSummaryList"),
        PaginatedMachineSummaryList,
    )


async def machine_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[MachineSummary]:
    """Lists machines, which represent items that teach moves to Pokémon. Use `limit` and
    `offset` to control the results page; `q` filters names case-insensitively and is
    available only in local deployments.

    Machines are the representation of items that teach moves to Pokémon. They vary from
    version to version, so it is not certain that one specific TM or HM corresponds to a
    single Machine.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await machine_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[MachineSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="machine_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMachineSummaryList"),
            PaginatedMachineSummaryList,
        )


async def machine_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedMachineSummaryList, MachineSummary]]:
    _page = await machine_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[MachineSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="machine_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMachineSummaryList"),
            PaginatedMachineSummaryList,
        )


def machine_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[MachineSummary]:
    """Lists machines, which represent items that teach moves to Pokémon. Use `limit` and
    `offset` to control the results page; `q` filters names case-insensitively and is
    available only in local deployments.

    Machines are the representation of items that teach moves to Pokémon. They vary from
    version to version, so it is not certain that one specific TM or HM corresponds to a
    single Machine.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = machine_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[MachineSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="machine_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMachineSummaryList"),
            PaginatedMachineSummaryList,
        )


def machine_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedMachineSummaryList, MachineSummary]]:
    _page = machine_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[MachineSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="machine_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMachineSummaryList"),
            PaginatedMachineSummaryList,
        )


async def machine_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> MachineDetail:
    """Retrieves a machine, which represents an item that teaches a move to a Pokémon. Use
    the `id` path parameter to identify the machine and retrieve its item, move, and
    version group.

    Machines are the representation of items that teach moves to Pokémon. They vary from
    version to version, so it is not certain that one specific TM or HM corresponds to a
    single Machine.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/machine/{encode_path_segment(id)}/",
        operation_id="machine_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "MachineDetail"), MachineDetail
    )


def machine_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> MachineDetail:
    """Retrieves a machine, which represents an item that teaches a move to a Pokémon. Use
    the `id` path parameter to identify the machine and retrieve its item, move, and
    version group.

    Machines are the representation of items that teach moves to Pokémon. They vary from
    version to version, so it is not certain that one specific TM or HM corresponds to a
    single Machine.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/machine/{encode_path_segment(id)}/",
        operation_id="machine_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "MachineDetail"), MachineDetail
    )


__all__ = [
    "machine_list",
    "machine_list_pages",
    "machine_list_pages_sync",
    "machine_list_paginated",
    "machine_list_paginated_sync",
    "machine_list_sync",
    "machine_retrieve",
    "machine_retrieve_sync",
]
