# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.machines import (
    machine_list,
    machine_list_pages,
    machine_list_pages_sync,
    machine_list_paginated,
    machine_list_paginated_sync,
    machine_list_sync,
    machine_retrieve,
    machine_retrieve_sync,
)


class _MachinesNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list = partial(machine_list, config)
        self.list.__doc__ = machine_list.__doc__
        self.list_sync = partial(machine_list_sync, config)
        self.list_sync.__doc__ = machine_list_sync.__doc__
        self.list_paginated = partial(machine_list_paginated, config)
        self.list_paginated.__doc__ = machine_list_paginated.__doc__
        self.list_pages = partial(machine_list_pages, config)
        self.list_pages.__doc__ = machine_list_pages.__doc__
        self.list_paginated_sync = partial(machine_list_paginated_sync, config)
        self.list_paginated_sync.__doc__ = machine_list_paginated_sync.__doc__
        self.list_pages_sync = partial(machine_list_pages_sync, config)
        self.list_pages_sync.__doc__ = machine_list_pages_sync.__doc__
        self.retrieve = partial(machine_retrieve, config)
        self.retrieve.__doc__ = machine_retrieve.__doc__
        self.retrieve_sync = partial(machine_retrieve_sync, config)
        self.retrieve_sync.__doc__ = machine_retrieve_sync.__doc__
