# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    LanguageDetail,
    LanguageSummary,
    PaginatedLanguageSummaryList,
    PokeapiMetaResponse,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def meta_retrieve(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> PokeapiMetaResponse:
    """Returns metadata about the currently deployed API version. Use the `deploy_date`,
    `hash`, and `tag` fields to identify the deployment; each value can be null.

    Returns metadata about the current deployed version of the API, including the git
    commit hash, deploy date, and tag (if any).
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/meta/",
        operation_id="meta_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokeapiMetaResponse"), PokeapiMetaResponse
    )


def meta_retrieve_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> PokeapiMetaResponse:
    """Returns metadata about the currently deployed API version. Use the `deploy_date`,
    `hash`, and `tag` fields to identify the deployment; each value can be null.

    Returns metadata about the current deployed version of the API, including the git
    commit hash, deploy date, and tag (if any).
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/meta/",
        operation_id="meta_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokeapiMetaResponse"), PokeapiMetaResponse
    )


async def language_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedLanguageSummaryList:
    """Lists languages used for translations of API resource information. Use `limit` and
    `offset` to control the result page, or `q` to filter languages by name with a
    case-insensitive query.

    Languages for translations of API resource information.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/language/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="language_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedLanguageSummaryList"),
        PaginatedLanguageSummaryList,
    )


def language_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedLanguageSummaryList:
    """Lists languages used for translations of API resource information. Use `limit` and
    `offset` to control the result page, or `q` to filter languages by name with a
    case-insensitive query.

    Languages for translations of API resource information.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/language/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="language_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedLanguageSummaryList"),
        PaginatedLanguageSummaryList,
    )


async def language_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[LanguageSummary]:
    """Lists languages used for translations of API resource information. Use `limit` and
    `offset` to control the result page, or `q` to filter languages by name with a
    case-insensitive query.

    Languages for translations of API resource information.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await language_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[LanguageSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="language_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedLanguageSummaryList"),
            PaginatedLanguageSummaryList,
        )


async def language_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedLanguageSummaryList, LanguageSummary]]:
    _page = await language_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[LanguageSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="language_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedLanguageSummaryList"),
            PaginatedLanguageSummaryList,
        )


def language_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[LanguageSummary]:
    """Lists languages used for translations of API resource information. Use `limit` and
    `offset` to control the result page, or `q` to filter languages by name with a
    case-insensitive query.

    Languages for translations of API resource information.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = language_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[LanguageSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="language_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedLanguageSummaryList"),
            PaginatedLanguageSummaryList,
        )


def language_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedLanguageSummaryList, LanguageSummary]]:
    _page = language_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[LanguageSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="language_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedLanguageSummaryList"),
            PaginatedLanguageSummaryList,
        )


async def language_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> LanguageDetail:
    """Retrieves a single language used for translations of API resource information. Use
    `id` to identify the language whose official status, ISO codes, and localized names
    you want to inspect.

    Languages for translations of API resource information.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/language/{encode_path_segment(id)}/",
        operation_id="language_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LanguageDetail"), LanguageDetail
    )


def language_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> LanguageDetail:
    """Retrieves a single language used for translations of API resource information. Use
    `id` to identify the language whose official status, ISO codes, and localized names
    you want to inspect.

    Languages for translations of API resource information.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/language/{encode_path_segment(id)}/",
        operation_id="language_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "LanguageDetail"), LanguageDetail
    )


__all__ = [
    "language_list",
    "language_list_pages",
    "language_list_pages_sync",
    "language_list_paginated",
    "language_list_paginated_sync",
    "language_list_sync",
    "language_retrieve",
    "language_retrieve_sync",
    "meta_retrieve",
    "meta_retrieve_sync",
]
