# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

WIRE_SCHEMAS_PART_1: dict[str, tuple[Any, dict[str, tuple[str, str | None]]]] = {
    "AbilityChange": (
        None,
        {
            "version_group": ("version_group", "VersionGroupSummary"),
            "effect_entries": ("effect_entries", "AbilityChangeEffectText"),
        },
    ),
    "AbilityChangeEffectText": (
        None,
        {
            "effect": ("effect", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "AbilityDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "is_main_series": ("is_main_series", None),
            "generation": ("generation", "GenerationSummary"),
            "names": ("names", "AbilityName"),
            "effect_entries": ("effect_entries", "AbilityEffectText"),
            "effect_changes": ("effect_changes", "AbilityChange"),
            "flavor_text_entries": ("flavor_text_entries", "AbilityFlavorText"),
            "pokemon": ("pokemon", "AbilityPokemonDetail"),
        },
    ),
    "AbilityEffectText": (
        None,
        {
            "effect": ("effect", None),
            "short_effect": ("short_effect", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "AbilityFlavorText": (
        None,
        {
            "flavor_text": ("flavor_text", None),
            "language": ("language", "LanguageSummary"),
            "version_group": ("version_group", "VersionGroupSummary"),
        },
    ),
    "AbilityName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "AbilityPokemonDetail": (
        None,
        {
            "is_hidden": ("is_hidden", None),
            "slot": ("slot", None),
            "pokemon": ("pokemon", "PokemonSummary"),
        },
    ),
    "AbilitySummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "BerryDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "growth_time": ("growth_time", None),
            "max_harvest": ("max_harvest", None),
            "natural_gift_power": ("natural_gift_power", None),
            "size": ("size", None),
            "smoothness": ("smoothness", None),
            "soil_dryness": ("soil_dryness", None),
            "firmness": ("firmness", "BerryFirmnessSummary"),
            "flavors": ("flavors", "BerryFlavorMap"),
            "item": ("item", "ItemSummary"),
            "natural_gift_type": ("natural_gift_type", "TypeSummary"),
        },
    ),
    "BerryFirmnessDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "berries": ("berries", "BerrySummary"),
            "names": ("names", "BerryFirmnessName"),
        },
    ),
    "BerryFirmnessName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "BerryFirmnessSummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "BerryFlavorBerryMap": (
        None,
        {
            "potency": ("potency", None),
            "berry": ("berry", "BerrySummary"),
        },
    ),
    "BerryFlavorDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "berries": ("berries", "BerryFlavorBerryMap"),
            "contest_type": ("contest_type", "ContestTypeSummary"),
            "names": ("names", "BerryFlavorName"),
        },
    ),
    "BerryFlavorMap": (
        None,
        {
            "potency": ("potency", None),
            "flavor": ("flavor", "BerryFlavorSummary"),
        },
    ),
    "BerryFlavorName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "BerryFlavorSummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "BerrySummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "CharacteristicDescription": (
        None,
        {
            "description": ("description", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "CharacteristicDetail": (
        None,
        {
            "id": ("id", None),
            "gene_modulo": ("gene_modulo", None),
            "possible_values": ("possible_values", None),
            "highest_stat": ("highest_stat", "StatSummary"),
            "descriptions": ("descriptions", "CharacteristicDescription"),
        },
    ),
    "CharacteristicSummary": (
        None,
        {
            "url": ("url", None),
        },
    ),
    "ContestEffectDetail": (
        None,
        {
            "id": ("id", None),
            "appeal": ("appeal", None),
            "jam": ("jam", None),
            "effect_entries": ("effect_entries", "ContestEffectEffectText"),
            "flavor_text_entries": ("flavor_text_entries", "ContestEffectFlavorText"),
        },
    ),
    "ContestEffectEffectText": (
        None,
        {
            "effect": ("effect", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "ContestEffectFlavorText": (
        None,
        {
            "flavor_text": ("flavor_text", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "ContestEffectSummary": (
        None,
        {
            "url": ("url", None),
        },
    ),
    "ContestTypeDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "berry_flavor": ("berry_flavor", "BerryFlavorSummary"),
            "names": ("names", "ContestTypeName"),
        },
    ),
    "ContestTypeName": (
        None,
        {
            "name": ("name", None),
            "color": ("color", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "ContestTypeSummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "CurrencyDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "names": ("names", "CurrencyName"),
        },
    ),
    "CurrencyName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "CurrencySummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "EggGroupDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "names": ("names", "EggGroupName"),
            "pokemon_species": ("pokemon_species", "PokemonSpeciesSummary"),
        },
    ),
    "EggGroupName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "EggGroupSummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "EncounterConditionDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "values": ("values", "EncounterConditionValueSummary"),
            "names": ("names", "EncounterConditionName"),
        },
    ),
    "EncounterConditionName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "EncounterConditionSummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "EncounterConditionValueDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "condition": ("condition", "EncounterConditionSummary"),
            "names": ("names", "EncounterConditionValueName"),
        },
    ),
    "EncounterConditionValueName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "EncounterConditionValueSummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "EncounterMethodDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "order": ("order", None),
            "names": ("names", "EncounterMethodName"),
        },
    ),
    "EncounterMethodName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
    "EncounterMethodSummary": (
        None,
        {
            "name": ("name", None),
            "url": ("url", None),
        },
    ),
    "EncounterPokemonDetail": (
        None,
        {
            "min_perfect_ivs": ("min_perfect_ivs", None),
            "always_shiny": ("always_shiny", None),
            "never_shiny": ("never_shiny", None),
            "is_alpha": ("is_alpha", None),
        },
    ),
    "EvolutionChainDetail": (
        None,
        {
            "id": ("id", None),
            "baby_trigger_item": ("baby_trigger_item", "ItemSummary"),
            "chain": ("chain", "EvolutionChainLink"),
        },
    ),
    "EvolutionChainLink": (
        None,
        {
            "is_baby": ("is_baby", None),
            "species": ("species", "PokemonSpeciesSummary"),
            "evolution_details": ("evolution_details", "PokemonEvolution"),
            "evolves_to": ("evolves_to", None),
        },
    ),
    "EvolutionChainSummary": (
        None,
        {
            "url": ("url", None),
        },
    ),
    "EvolutionConditionExpression": (
        None,
        {
            "expression": ("expression", None),
            "percentage_chance": ("percentage_chance", None),
            "variables": ("variables", "EvolutionVariableSummary"),
        },
    ),
    "EvolutionTriggerDetail": (
        None,
        {
            "id": ("id", None),
            "name": ("name", None),
            "names": ("names", "EvolutionTriggerName"),
            "pokemon_species": ("pokemon_species", "PokemonSpeciesSummary"),
        },
    ),
    "EvolutionTriggerName": (
        None,
        {
            "name": ("name", None),
            "language": ("language", "LanguageSummary"),
        },
    ),
}
