# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    PaginatedPokemonHabitatSummaryList,
    PaginatedPokemonShapeSummaryList,
    PokemonHabitatDetail,
    PokemonHabitatSummary,
    PokemonShapeDetail,
    PokemonShapeSummary,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def pokemon_habitat_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonHabitatSummaryList:
    """Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas
    designated for rare or legendary Pokémon. Use `limit` and `offset` to page through
    results, or use `q` to filter by name; `q` is available only on local installations.

    Habitats are generally different terrain Pokémon can be found in but can also be
    areas designated for rare or legendary Pokémon.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/pokemon-habitat/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_habitat_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonHabitatSummaryList"),
        PaginatedPokemonHabitatSummaryList,
    )


def pokemon_habitat_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonHabitatSummaryList:
    """Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas
    designated for rare or legendary Pokémon. Use `limit` and `offset` to page through
    results, or use `q` to filter by name; `q` is available only on local installations.

    Habitats are generally different terrain Pokémon can be found in but can also be
    areas designated for rare or legendary Pokémon.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/pokemon-habitat/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_habitat_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonHabitatSummaryList"),
        PaginatedPokemonHabitatSummaryList,
    )


async def pokemon_habitat_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[PokemonHabitatSummary]:
    """Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas
    designated for rare or legendary Pokémon. Use `limit` and `offset` to page through
    results, or use `q` to filter by name; `q` is available only on local installations.

    Habitats are generally different terrain Pokémon can be found in but can also be
    areas designated for rare or legendary Pokémon.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await pokemon_habitat_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonHabitatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_habitat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonHabitatSummaryList"),
            PaginatedPokemonHabitatSummaryList,
        )


async def pokemon_habitat_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedPokemonHabitatSummaryList, PokemonHabitatSummary]]:
    _page = await pokemon_habitat_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonHabitatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_habitat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonHabitatSummaryList"),
            PaginatedPokemonHabitatSummaryList,
        )


def pokemon_habitat_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[PokemonHabitatSummary]:
    """Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas
    designated for rare or legendary Pokémon. Use `limit` and `offset` to page through
    results, or use `q` to filter by name; `q` is available only on local installations.

    Habitats are generally different terrain Pokémon can be found in but can also be
    areas designated for rare or legendary Pokémon.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = pokemon_habitat_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonHabitatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_habitat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonHabitatSummaryList"),
            PaginatedPokemonHabitatSummaryList,
        )


def pokemon_habitat_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedPokemonHabitatSummaryList, PokemonHabitatSummary]]:
    _page = pokemon_habitat_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonHabitatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_habitat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonHabitatSummaryList"),
            PaginatedPokemonHabitatSummaryList,
        )


async def pokemon_habitat_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonHabitatDetail:
    """Retrieves a Pokémon habitat, which describes terrain where Pokémon can be found or
    an area designated for rare or legendary Pokémon. Use `id` to select a habitat and
    view its localized names and associated Pokémon species.

    Habitats are generally different terrain Pokémon can be found in but can also be
    areas designated for rare or legendary Pokémon.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/pokemon-habitat/{encode_path_segment(id)}/",
        operation_id="pokemon_habitat_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonHabitatDetail"), PokemonHabitatDetail
    )


def pokemon_habitat_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonHabitatDetail:
    """Retrieves a Pokémon habitat, which describes terrain where Pokémon can be found or
    an area designated for rare or legendary Pokémon. Use `id` to select a habitat and
    view its localized names and associated Pokémon species.

    Habitats are generally different terrain Pokémon can be found in but can also be
    areas designated for rare or legendary Pokémon.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/pokemon-habitat/{encode_path_segment(id)}/",
        operation_id="pokemon_habitat_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonHabitatDetail"), PokemonHabitatDetail
    )


async def pokemon_shape_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonShapeSummaryList:
    """Lists shapes used to sort Pokémon in a Pokédex. Use `limit` and `offset` to page
    through results, or use `q` to filter shapes by name; `q` is available only on local
    installations.

    Shapes used for sorting Pokémon in a Pokédex.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/pokemon-shape/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_shape_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonShapeSummaryList"),
        PaginatedPokemonShapeSummaryList,
    )


def pokemon_shape_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonShapeSummaryList:
    """Lists shapes used to sort Pokémon in a Pokédex. Use `limit` and `offset` to page
    through results, or use `q` to filter shapes by name; `q` is available only on local
    installations.

    Shapes used for sorting Pokémon in a Pokédex.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/pokemon-shape/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_shape_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonShapeSummaryList"),
        PaginatedPokemonShapeSummaryList,
    )


async def pokemon_shape_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[PokemonShapeSummary]:
    """Lists shapes used to sort Pokémon in a Pokédex. Use `limit` and `offset` to page
    through results, or use `q` to filter shapes by name; `q` is available only on local
    installations.

    Shapes used for sorting Pokémon in a Pokédex.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await pokemon_shape_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonShapeSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_shape_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonShapeSummaryList"),
            PaginatedPokemonShapeSummaryList,
        )


async def pokemon_shape_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedPokemonShapeSummaryList, PokemonShapeSummary]]:
    _page = await pokemon_shape_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonShapeSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_shape_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonShapeSummaryList"),
            PaginatedPokemonShapeSummaryList,
        )


def pokemon_shape_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[PokemonShapeSummary]:
    """Lists shapes used to sort Pokémon in a Pokédex. Use `limit` and `offset` to page
    through results, or use `q` to filter shapes by name; `q` is available only on local
    installations.

    Shapes used for sorting Pokémon in a Pokédex.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = pokemon_shape_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonShapeSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_shape_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonShapeSummaryList"),
            PaginatedPokemonShapeSummaryList,
        )


def pokemon_shape_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedPokemonShapeSummaryList, PokemonShapeSummary]]:
    _page = pokemon_shape_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonShapeSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_shape_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonShapeSummaryList"),
            PaginatedPokemonShapeSummaryList,
        )


async def pokemon_shape_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonShapeDetail:
    """Retrieves a Pokémon shape used to sort Pokémon in a Pokédex. Use `id` to select a
    shape and view its localized names, alternative shape names, and associated Pokémon
    species.

    Shapes used for sorting Pokémon in a Pokédex.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/pokemon-shape/{encode_path_segment(id)}/",
        operation_id="pokemon_shape_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonShapeDetail"), PokemonShapeDetail
    )


def pokemon_shape_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonShapeDetail:
    """Retrieves a Pokémon shape used to sort Pokémon in a Pokédex. Use `id` to select a
    shape and view its localized names, alternative shape names, and associated Pokémon
    species.

    Shapes used for sorting Pokémon in a Pokédex.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/pokemon-shape/{encode_path_segment(id)}/",
        operation_id="pokemon_shape_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonShapeDetail"), PokemonShapeDetail
    )


__all__ = [
    "pokemon_habitat_list",
    "pokemon_habitat_list_pages",
    "pokemon_habitat_list_pages_sync",
    "pokemon_habitat_list_paginated",
    "pokemon_habitat_list_paginated_sync",
    "pokemon_habitat_list_sync",
    "pokemon_habitat_retrieve",
    "pokemon_habitat_retrieve_sync",
    "pokemon_shape_list",
    "pokemon_shape_list_pages",
    "pokemon_shape_list_pages_sync",
    "pokemon_shape_list_paginated",
    "pokemon_shape_list_paginated_sync",
    "pokemon_shape_list_sync",
    "pokemon_shape_retrieve",
    "pokemon_shape_retrieve_sync",
]
