# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    PaginatedPokeathlonStatSummaryList,
    PaginatedPokemonSpeciesSummaryList,
    PokeathlonStatDetail,
    PokeathlonStatSummary,
    PokemonSpeciesDetail,
    PokemonSpeciesSummary,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def pokemon_species_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonSpeciesSummaryList:
    """Lists Pokémon species, whose shared attributes apply across the varieties within
    each species. Use `limit` and `offset` to page through results, or use `q` to filter
    species by name; `q` is available only on local installations.

    A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon
    species are shared across all varieties of Pokémon within the species. A good
    example is Wormadam; Wormadam is the species which can be found in three different
    varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/pokemon-species/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_species_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonSpeciesSummaryList"),
        PaginatedPokemonSpeciesSummaryList,
    )


def pokemon_species_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonSpeciesSummaryList:
    """Lists Pokémon species, whose shared attributes apply across the varieties within
    each species. Use `limit` and `offset` to page through results, or use `q` to filter
    species by name; `q` is available only on local installations.

    A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon
    species are shared across all varieties of Pokémon within the species. A good
    example is Wormadam; Wormadam is the species which can be found in three different
    varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/pokemon-species/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_species_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonSpeciesSummaryList"),
        PaginatedPokemonSpeciesSummaryList,
    )


async def pokemon_species_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[PokemonSpeciesSummary]:
    """Lists Pokémon species, whose shared attributes apply across the varieties within
    each species. Use `limit` and `offset` to page through results, or use `q` to filter
    species by name; `q` is available only on local installations.

    A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon
    species are shared across all varieties of Pokémon within the species. A good
    example is Wormadam; Wormadam is the species which can be found in three different
    varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await pokemon_species_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonSpeciesSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_species_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonSpeciesSummaryList"),
            PaginatedPokemonSpeciesSummaryList,
        )


async def pokemon_species_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedPokemonSpeciesSummaryList, PokemonSpeciesSummary]]:
    _page = await pokemon_species_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonSpeciesSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_species_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonSpeciesSummaryList"),
            PaginatedPokemonSpeciesSummaryList,
        )


def pokemon_species_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[PokemonSpeciesSummary]:
    """Lists Pokémon species, whose shared attributes apply across the varieties within
    each species. Use `limit` and `offset` to page through results, or use `q` to filter
    species by name; `q` is available only on local installations.

    A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon
    species are shared across all varieties of Pokémon within the species. A good
    example is Wormadam; Wormadam is the species which can be found in three different
    varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = pokemon_species_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonSpeciesSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_species_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonSpeciesSummaryList"),
            PaginatedPokemonSpeciesSummaryList,
        )


def pokemon_species_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedPokemonSpeciesSummaryList, PokemonSpeciesSummary]]:
    _page = pokemon_species_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonSpeciesSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_species_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonSpeciesSummaryList"),
            PaginatedPokemonSpeciesSummaryList,
        )


async def pokemon_species_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonSpeciesDetail:
    """Retrieves a Pokémon species, whose attributes are shared across its Pokémon
    varieties. Use `id` to select a species and inspect its generation, growth rate,
    habitat, egg groups, Pokédex numbers, and other species attributes.

    A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon
    species are shared across all varieties of Pokémon within the species. A good
    example is Wormadam; Wormadam is the species which can be found in three different
    varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/pokemon-species/{encode_path_segment(id)}/",
        operation_id="pokemon_species_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonSpeciesDetail"), PokemonSpeciesDetail
    )


def pokemon_species_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonSpeciesDetail:
    """Retrieves a Pokémon species, whose attributes are shared across its Pokémon
    varieties. Use `id` to select a species and inspect its generation, growth rate,
    habitat, egg groups, Pokédex numbers, and other species attributes.

    A Pokémon Species forms the basis for at least one Pokémon. Attributes of a Pokémon
    species are shared across all varieties of Pokémon within the species. A good
    example is Wormadam; Wormadam is the species which can be found in three different
    varieties, Wormadam-Trash, Wormadam-Sandy and Wormadam-Plant.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/pokemon-species/{encode_path_segment(id)}/",
        operation_id="pokemon_species_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonSpeciesDetail"), PokemonSpeciesDetail
    )


async def pokeathlon_stat_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokeathlonStatSummaryList:
    """Lists Pokéathlon stats, which describe different attributes of a Pokémon's
    performance in Pokéathlons. Use `limit` and `offset` to page through results, or use
    `q` to filter stats by name; `q` is available only on local installations.

    Pokeathlon Stats are different attributes of a Pokémon's performance in Pokéathlons.
    In Pokéathlons, competitions happen on different courses; one for each of the
    different Pokéathlon stats. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/pokeathlon-stat/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokeathlon_stat_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokeathlonStatSummaryList"),
        PaginatedPokeathlonStatSummaryList,
    )


def pokeathlon_stat_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokeathlonStatSummaryList:
    """Lists Pokéathlon stats, which describe different attributes of a Pokémon's
    performance in Pokéathlons. Use `limit` and `offset` to page through results, or use
    `q` to filter stats by name; `q` is available only on local installations.

    Pokeathlon Stats are different attributes of a Pokémon's performance in Pokéathlons.
    In Pokéathlons, competitions happen on different courses; one for each of the
    different Pokéathlon stats. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/pokeathlon-stat/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokeathlon_stat_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokeathlonStatSummaryList"),
        PaginatedPokeathlonStatSummaryList,
    )


async def pokeathlon_stat_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[PokeathlonStatSummary]:
    """Lists Pokéathlon stats, which describe different attributes of a Pokémon's
    performance in Pokéathlons. Use `limit` and `offset` to page through results, or use
    `q` to filter stats by name; `q` is available only on local installations.

    Pokeathlon Stats are different attributes of a Pokémon's performance in Pokéathlons.
    In Pokéathlons, competitions happen on different courses; one for each of the
    different Pokéathlon stats. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await pokeathlon_stat_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokeathlonStatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokeathlon_stat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokeathlonStatSummaryList"),
            PaginatedPokeathlonStatSummaryList,
        )


async def pokeathlon_stat_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedPokeathlonStatSummaryList, PokeathlonStatSummary]]:
    _page = await pokeathlon_stat_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokeathlonStatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokeathlon_stat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokeathlonStatSummaryList"),
            PaginatedPokeathlonStatSummaryList,
        )


def pokeathlon_stat_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[PokeathlonStatSummary]:
    """Lists Pokéathlon stats, which describe different attributes of a Pokémon's
    performance in Pokéathlons. Use `limit` and `offset` to page through results, or use
    `q` to filter stats by name; `q` is available only on local installations.

    Pokeathlon Stats are different attributes of a Pokémon's performance in Pokéathlons.
    In Pokéathlons, competitions happen on different courses; one for each of the
    different Pokéathlon stats. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = pokeathlon_stat_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokeathlonStatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokeathlon_stat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokeathlonStatSummaryList"),
            PaginatedPokeathlonStatSummaryList,
        )


def pokeathlon_stat_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedPokeathlonStatSummaryList, PokeathlonStatSummary]]:
    _page = pokeathlon_stat_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokeathlonStatSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokeathlon_stat_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokeathlonStatSummaryList"),
            PaginatedPokeathlonStatSummaryList,
        )


async def pokeathlon_stat_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokeathlonStatDetail:
    """Retrieves a Pokéathlon stat, which represents an attribute of a Pokémon's
    performance in Pokéathlons. Use `id` to select a stat and view its localized names
    and the natures that affect it.

    Pokeathlon Stats are different attributes of a Pokémon's performance in Pokéathlons.
    In Pokéathlons, competitions happen on different courses; one for each of the
    different Pokéathlon stats. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/pokeathlon-stat/{encode_path_segment(id)}/",
        operation_id="pokeathlon_stat_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokeathlonStatDetail"), PokeathlonStatDetail
    )


def pokeathlon_stat_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokeathlonStatDetail:
    """Retrieves a Pokéathlon stat, which represents an attribute of a Pokémon's
    performance in Pokéathlons. Use `id` to select a stat and view its localized names
    and the natures that affect it.

    Pokeathlon Stats are different attributes of a Pokémon's performance in Pokéathlons.
    In Pokéathlons, competitions happen on different courses; one for each of the
    different Pokéathlon stats. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9athlon) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/pokeathlon-stat/{encode_path_segment(id)}/",
        operation_id="pokeathlon_stat_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokeathlonStatDetail"), PokeathlonStatDetail
    )


__all__ = [
    "pokeathlon_stat_list",
    "pokeathlon_stat_list_pages",
    "pokeathlon_stat_list_pages_sync",
    "pokeathlon_stat_list_paginated",
    "pokeathlon_stat_list_paginated_sync",
    "pokeathlon_stat_list_sync",
    "pokeathlon_stat_retrieve",
    "pokeathlon_stat_retrieve_sync",
    "pokemon_species_list",
    "pokemon_species_list_pages",
    "pokemon_species_list_pages_sync",
    "pokemon_species_list_paginated",
    "pokemon_species_list_paginated_sync",
    "pokemon_species_list_sync",
    "pokemon_species_retrieve",
    "pokemon_species_retrieve_sync",
]
