# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    PaginatedPokemonColorSummaryList,
    PaginatedPokemonFormSummaryList,
    PokemonColorDetail,
    PokemonColorSummary,
    PokemonFormDetail,
    PokemonFormSummary,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def pokemon_color_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonColorSummaryList:
    """Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate
    the results, or use `q` to search color names when running the API locally.

    Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is
    usually the color most apparent or covering each Pokémon's body. No orange category
    exists; Pokémon that are primarily orange are listed as red or brown.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/pokemon-color/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_color_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonColorSummaryList"),
        PaginatedPokemonColorSummaryList,
    )


def pokemon_color_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonColorSummaryList:
    """Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate
    the results, or use `q` to search color names when running the API locally.

    Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is
    usually the color most apparent or covering each Pokémon's body. No orange category
    exists; Pokémon that are primarily orange are listed as red or brown.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/pokemon-color/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_color_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonColorSummaryList"),
        PaginatedPokemonColorSummaryList,
    )


async def pokemon_color_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[PokemonColorSummary]:
    """Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate
    the results, or use `q` to search color names when running the API locally.

    Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is
    usually the color most apparent or covering each Pokémon's body. No orange category
    exists; Pokémon that are primarily orange are listed as red or brown.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await pokemon_color_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonColorSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_color_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonColorSummaryList"),
            PaginatedPokemonColorSummaryList,
        )


async def pokemon_color_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedPokemonColorSummaryList, PokemonColorSummary]]:
    _page = await pokemon_color_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonColorSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_color_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonColorSummaryList"),
            PaginatedPokemonColorSummaryList,
        )


def pokemon_color_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[PokemonColorSummary]:
    """Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate
    the results, or use `q` to search color names when running the API locally.

    Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is
    usually the color most apparent or covering each Pokémon's body. No orange category
    exists; Pokémon that are primarily orange are listed as red or brown.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = pokemon_color_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonColorSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_color_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonColorSummaryList"),
            PaginatedPokemonColorSummaryList,
        )


def pokemon_color_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedPokemonColorSummaryList, PokemonColorSummary]]:
    _page = pokemon_color_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonColorSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_color_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonColorSummaryList"),
            PaginatedPokemonColorSummaryList,
        )


async def pokemon_color_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonColorDetail:
    """Retrieves a Pokémon color record and the species associated with that color. Use the
    color identifier to look up its localized names and related Pokémon species.

    Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is
    usually the color most apparent or covering each Pokémon's body. No orange category
    exists; Pokémon that are primarily orange are listed as red or brown.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/pokemon-color/{encode_path_segment(id)}/",
        operation_id="pokemon_color_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonColorDetail"), PokemonColorDetail
    )


def pokemon_color_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonColorDetail:
    """Retrieves a Pokémon color record and the species associated with that color. Use the
    color identifier to look up its localized names and related Pokémon species.

    Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is
    usually the color most apparent or covering each Pokémon's body. No orange category
    exists; Pokémon that are primarily orange are listed as red or brown.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/pokemon-color/{encode_path_segment(id)}/",
        operation_id="pokemon_color_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonColorDetail"), PokemonColorDetail
    )


async def pokemon_form_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonFormSummaryList:
    """Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to
    paginate the results, or use `q` to search form names when running the API locally.

    Some Pokémon may appear in one of multiple, visually different forms. These
    differences are purely cosmetic. For variations within a Pokémon species, which do
    differ in more than just visuals, the 'Pokémon' entity is used to represent such a
    variety.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/pokemon-form/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_form_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonFormSummaryList"),
        PaginatedPokemonFormSummaryList,
    )


def pokemon_form_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokemonFormSummaryList:
    """Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to
    paginate the results, or use `q` to search form names when running the API locally.

    Some Pokémon may appear in one of multiple, visually different forms. These
    differences are purely cosmetic. For variations within a Pokémon species, which do
    differ in more than just visuals, the 'Pokémon' entity is used to represent such a
    variety.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/pokemon-form/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokemon_form_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokemonFormSummaryList"),
        PaginatedPokemonFormSummaryList,
    )


async def pokemon_form_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[PokemonFormSummary]:
    """Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to
    paginate the results, or use `q` to search form names when running the API locally.

    Some Pokémon may appear in one of multiple, visually different forms. These
    differences are purely cosmetic. For variations within a Pokémon species, which do
    differ in more than just visuals, the 'Pokémon' entity is used to represent such a
    variety.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await pokemon_form_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonFormSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_form_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonFormSummaryList"),
            PaginatedPokemonFormSummaryList,
        )


async def pokemon_form_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedPokemonFormSummaryList, PokemonFormSummary]]:
    _page = await pokemon_form_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonFormSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokemon_form_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonFormSummaryList"),
            PaginatedPokemonFormSummaryList,
        )


def pokemon_form_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[PokemonFormSummary]:
    """Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to
    paginate the results, or use `q` to search form names when running the API locally.

    Some Pokémon may appear in one of multiple, visually different forms. These
    differences are purely cosmetic. For variations within a Pokémon species, which do
    differ in more than just visuals, the 'Pokémon' entity is used to represent such a
    variety.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = pokemon_form_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonFormSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_form_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonFormSummaryList"),
            PaginatedPokemonFormSummaryList,
        )


def pokemon_form_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedPokemonFormSummaryList, PokemonFormSummary]]:
    _page = pokemon_form_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[PokemonFormSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokemon_form_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokemonFormSummaryList"),
            PaginatedPokemonFormSummaryList,
        )


async def pokemon_form_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonFormDetail:
    """Retrieves a Pokémon form, which represents a cosmetic variation of a Pokémon. Use
    `id` to select the form and inspect its Pokémon, version group, types, localized
    names, and trigger conditions.

    Some Pokémon may appear in one of multiple, visually different forms. These
    differences are purely cosmetic. For variations within a Pokémon species, which do
    differ in more than just visuals, the 'Pokémon' entity is used to represent such a
    variety.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/pokemon-form/{encode_path_segment(id)}/",
        operation_id="pokemon_form_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonFormDetail"), PokemonFormDetail
    )


def pokemon_form_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokemonFormDetail:
    """Retrieves a Pokémon form, which represents a cosmetic variation of a Pokémon. Use
    `id` to select the form and inspect its Pokémon, version group, types, localized
    names, and trigger conditions.

    Some Pokémon may appear in one of multiple, visually different forms. These
    differences are purely cosmetic. For variations within a Pokémon species, which do
    differ in more than just visuals, the 'Pokémon' entity is used to represent such a
    variety.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/pokemon-form/{encode_path_segment(id)}/",
        operation_id="pokemon_form_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokemonFormDetail"), PokemonFormDetail
    )


__all__ = [
    "pokemon_color_list",
    "pokemon_color_list_pages",
    "pokemon_color_list_pages_sync",
    "pokemon_color_list_paginated",
    "pokemon_color_list_paginated_sync",
    "pokemon_color_list_sync",
    "pokemon_color_retrieve",
    "pokemon_color_retrieve_sync",
    "pokemon_form_list",
    "pokemon_form_list_pages",
    "pokemon_form_list_pages_sync",
    "pokemon_form_list_paginated",
    "pokemon_form_list_paginated_sync",
    "pokemon_form_list_sync",
    "pokemon_form_retrieve",
    "pokemon_form_retrieve_sync",
]
