# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    AbilityDetail,
    AbilitySummary,
    CharacteristicDetail,
    CharacteristicSummary,
    PaginatedAbilitySummaryList,
    PaginatedCharacteristicSummaryList,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def ability_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedAbilitySummaryList:
    """Lists abilities, which provide passive effects for Pokémon in battle or in the
    overworld. Use `limit` and `offset` to select a result window, and `q` to filter by
    name when running a local API instance.

    Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon
    have multiple possible abilities but can have only one ability at a time. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/ability/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="ability_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedAbilitySummaryList"),
        PaginatedAbilitySummaryList,
    )


def ability_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedAbilitySummaryList:
    """Lists abilities, which provide passive effects for Pokémon in battle or in the
    overworld. Use `limit` and `offset` to select a result window, and `q` to filter by
    name when running a local API instance.

    Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon
    have multiple possible abilities but can have only one ability at a time. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/ability/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="ability_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedAbilitySummaryList"),
        PaginatedAbilitySummaryList,
    )


async def ability_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[AbilitySummary]:
    """Lists abilities, which provide passive effects for Pokémon in battle or in the
    overworld. Use `limit` and `offset` to select a result window, and `q` to filter by
    name when running a local API instance.

    Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon
    have multiple possible abilities but can have only one ability at a time. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await ability_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[AbilitySummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="ability_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedAbilitySummaryList"),
            PaginatedAbilitySummaryList,
        )


async def ability_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedAbilitySummaryList, AbilitySummary]]:
    _page = await ability_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[AbilitySummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="ability_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedAbilitySummaryList"),
            PaginatedAbilitySummaryList,
        )


def ability_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[AbilitySummary]:
    """Lists abilities, which provide passive effects for Pokémon in battle or in the
    overworld. Use `limit` and `offset` to select a result window, and `q` to filter by
    name when running a local API instance.

    Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon
    have multiple possible abilities but can have only one ability at a time. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = ability_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[AbilitySummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="ability_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedAbilitySummaryList"),
            PaginatedAbilitySummaryList,
        )


def ability_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedAbilitySummaryList, AbilitySummary]]:
    _page = ability_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[AbilitySummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="ability_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedAbilitySummaryList"),
            PaginatedAbilitySummaryList,
        )


async def ability_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> AbilityDetail:
    """Retrieves a single ability and its Pokémon, generation, effect, and localized text
    data. Supply the ability's `id` as a string or integer to look up the record.

    Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon
    have multiple possible abilities but can have only one ability at a time. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/ability/{encode_path_segment(id)}/",
        operation_id="ability_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "AbilityDetail"), AbilityDetail
    )


def ability_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> AbilityDetail:
    """Retrieves a single ability and its Pokémon, generation, effect, and localized text
    data. Supply the ability's `id` as a string or integer to look up the record.

    Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon
    have multiple possible abilities but can have only one ability at a time. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Ability) for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/ability/{encode_path_segment(id)}/",
        operation_id="ability_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "AbilityDetail"), AbilityDetail
    )


async def characteristic_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedCharacteristicSummaryList:
    """Lists characteristics that indicate which stat contains a Pokémon's highest
    individual value (IV). Use `limit` and `offset` to select a result window, and `q`
    to filter characteristics by name on a local API instance.

    Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's
    Characteristic is determined by the remainder of its highest IV divided by 5
    (gene_modulo). Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/characteristic/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="characteristic_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedCharacteristicSummaryList"),
        PaginatedCharacteristicSummaryList,
    )


def characteristic_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedCharacteristicSummaryList:
    """Lists characteristics that indicate which stat contains a Pokémon's highest
    individual value (IV). Use `limit` and `offset` to select a result window, and `q`
    to filter characteristics by name on a local API instance.

    Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's
    Characteristic is determined by the remainder of its highest IV divided by 5
    (gene_modulo). Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/characteristic/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="characteristic_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedCharacteristicSummaryList"),
        PaginatedCharacteristicSummaryList,
    )


async def characteristic_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[CharacteristicSummary]:
    """Lists characteristics that indicate which stat contains a Pokémon's highest
    individual value (IV). Use `limit` and `offset` to select a result window, and `q`
    to filter characteristics by name on a local API instance.

    Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's
    Characteristic is determined by the remainder of its highest IV divided by 5
    (gene_modulo). Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await characteristic_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[CharacteristicSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="characteristic_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedCharacteristicSummaryList"),
            PaginatedCharacteristicSummaryList,
        )


async def characteristic_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedCharacteristicSummaryList, CharacteristicSummary]]:
    _page = await characteristic_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[CharacteristicSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="characteristic_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedCharacteristicSummaryList"),
            PaginatedCharacteristicSummaryList,
        )


def characteristic_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[CharacteristicSummary]:
    """Lists characteristics that indicate which stat contains a Pokémon's highest
    individual value (IV). Use `limit` and `offset` to select a result window, and `q`
    to filter characteristics by name on a local API instance.

    Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's
    Characteristic is determined by the remainder of its highest IV divided by 5
    (gene_modulo). Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = characteristic_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[CharacteristicSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="characteristic_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedCharacteristicSummaryList"),
            PaginatedCharacteristicSummaryList,
        )


def characteristic_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedCharacteristicSummaryList, CharacteristicSummary]]:
    _page = characteristic_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[CharacteristicSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="characteristic_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedCharacteristicSummaryList"),
            PaginatedCharacteristicSummaryList,
        )


async def characteristic_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> CharacteristicDetail:
    """Retrieves the characteristic that describes which stat contains a Pokémon's highest
    IV. Use the `id` path parameter to select a characteristic and read its gene modulo,
    possible values, highest stat, and localized descriptions.

    Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's
    Characteristic is determined by the remainder of its highest IV divided by 5
    (gene_modulo). Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/characteristic/{encode_path_segment(id)}/",
        operation_id="characteristic_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CharacteristicDetail"), CharacteristicDetail
    )


def characteristic_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> CharacteristicDetail:
    """Retrieves the characteristic that describes which stat contains a Pokémon's highest
    IV. Use the `id` path parameter to select a characteristic and read its gene modulo,
    possible values, highest stat, and localized descriptions.

    Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's
    Characteristic is determined by the remainder of its highest IV divided by 5
    (gene_modulo). Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Characteristic) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/characteristic/{encode_path_segment(id)}/",
        operation_id="characteristic_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CharacteristicDetail"), CharacteristicDetail
    )


__all__ = [
    "ability_list",
    "ability_list_pages",
    "ability_list_pages_sync",
    "ability_list_paginated",
    "ability_list_paginated_sync",
    "ability_list_sync",
    "ability_retrieve",
    "ability_retrieve_sync",
    "characteristic_list",
    "characteristic_list_pages",
    "characteristic_list_pages_sync",
    "characteristic_list_paginated",
    "characteristic_list_paginated_sync",
    "characteristic_list_sync",
    "characteristic_retrieve",
    "characteristic_retrieve_sync",
]
