# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from sdk.client import NOT_GIVEN, NotGiven
from sdk.types.shared import (
    EncounterConditionValueSummary,
    EncounterMethodSummary,
    LanguageSummary,
    LocationAreaSummary,
    VersionSummary,
)

from ..validation import validate_length, validate_range, validate_required, validate_uri


class EncounterConditionDetail(BaseModel):
    """Typed representation of the `EncounterConditionDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    values: list[EncounterConditionValueSummary]
    """Required array value serialized in the `values` wire field."""
    names: list[EncounterConditionName]
    """Required array value serialized in the `names` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["id", "name", "names", "values"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class EncounterConditionName(BaseModel):
    """Typed representation of the `EncounterConditionName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class EncounterConditionSummary(BaseModel):
    """Typed representation of the `EncounterConditionSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class EncounterConditionValueDetail(BaseModel):
    """Typed representation of the `EncounterConditionValueDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    condition: EncounterConditionSummary
    """Required object value serialized in the `condition` wire field."""
    names: list[EncounterConditionValueName]
    """Required array value serialized in the `names` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["condition", "id", "name", "names"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class EncounterConditionValueName(BaseModel):
    """Typed representation of the `EncounterConditionValueName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class EncounterMethodDetail(BaseModel):
    """Typed representation of the `EncounterMethodDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    names: list[EncounterMethodName]
    """Required array value serialized in the `names` wire field."""
    order: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `order` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["id", "name", "names"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("order")
    @classmethod
    def _validate_order(cls, value):
        if value is not None:
            validate_range("order", value, min=-2147483648, max=2147483647)
        return value


class EncounterMethodName(BaseModel):
    """Typed representation of the `EncounterMethodName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PaginatedEncounterConditionSummaryList(BaseModel):
    """Typed representation of the `PaginatedEncounterConditionSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[EncounterConditionSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedEncounterConditionValueSummaryList(BaseModel):
    """Typed representation of the `PaginatedEncounterConditionValueSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[EncounterConditionValueSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedEncounterMethodSummaryList(BaseModel):
    """Typed representation of the `PaginatedEncounterMethodSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[EncounterMethodSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PokemonEncounterDetailResponse(BaseModel):
    """Typed representation of the `PokemonEncounterDetailResponse` API schema."""

    chance: int
    """Required `integer` value serialized in the `chance` wire field."""
    condition_values: list[EncounterConditionValueSummary]
    """Required array value serialized in the `condition_values` wire field."""
    max_level: int
    """Required `integer` value serialized in the `max_level` wire field."""
    method: EncounterMethodSummary
    """Required object value serialized in the `method` wire field."""
    min_level: int
    """Required `integer` value serialized in the `min_level` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["chance", "condition_values", "max_level", "method", "min_level"])
        return value


class PokemonEncounterResponse(BaseModel):
    """Typed representation of the `PokemonEncounterResponse` API schema."""

    location_area: LocationAreaSummary
    """Required object value serialized in the `location_area` wire field."""
    version_details: list[PokemonEncounterVersionDetailResponse]
    """Required array value serialized in the `version_details` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["location_area", "version_details"])
        return value


class PokemonEncounterVersionDetailResponse(BaseModel):
    """Typed representation of the `PokemonEncounterVersionDetailResponse` API schema."""

    version: VersionSummary
    """Required object value serialized in the `version` wire field."""
    max_chance: int
    """Required `integer` value serialized in the `max_chance` wire field."""
    encounter_details: list[PokemonEncounterDetailResponse]
    """Required array value serialized in the `encounter_details` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["encounter_details", "max_chance", "version"])
        return value
