# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from sdk.client import NOT_GIVEN, NotGiven
from sdk.types.evolution_part001 import EvolutionConditionExpression, EvolutionTriggerSummary
from sdk.types.shared import (
    ItemSummary,
    LocationSummary,
    MoveSummary,
    NatureSummary,
    PokemonFormSummary,
    PokemonSpeciesSummary,
    RegionSummary,
    TypeSummary,
    VersionGroupSummary,
)

from ..validation import validate_length, validate_range, validate_required


class PokemonEvolution(BaseModel):
    """Typed representation of the `PokemonEvolution` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    version_group: VersionGroupSummary
    """Required object value serialized in the `version_group` wire field."""
    item: ItemSummary
    """Required object value serialized in the `item` wire field."""
    trigger: EvolutionTriggerSummary
    """Required object value serialized in the `trigger` wire field."""
    held_item: ItemSummary
    """Required object value serialized in the `held_item` wire field."""
    known_move: MoveSummary
    """Required object value serialized in the `known_move` wire field."""
    known_move_type: TypeSummary
    """Required object value serialized in the `known_move_type` wire field."""
    location: LocationSummary
    """Required object value serialized in the `location` wire field."""
    party_species: PokemonSpeciesSummary
    """Required object value serialized in the `party_species` wire field."""
    party_type: TypeSummary
    """Required object value serialized in the `party_type` wire field."""
    trade_species: PokemonSpeciesSummary
    """Required object value serialized in the `trade_species` wire field."""
    region: RegionSummary
    """Required object value serialized in the `region` wire field."""
    required_pokemon_form: PokemonFormSummary
    """Required object value serialized in the `required_pokemon_form` wire field."""
    evolved_pokemon_form: PokemonFormSummary
    """Required object value serialized in the `evolved_pokemon_form` wire field."""
    used_move: MoveSummary
    """Required object value serialized in the `used_move` wire field."""
    allowed_natures: list[NatureSummary]
    """Required array value serialized in the `allowed_natures` wire field."""
    condition_expression: EvolutionConditionExpression | None
    """Required API value serialized in the `condition_expression` wire field."""
    is_default: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_default` wire field."""
    gender: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `gender` wire field."""
    min_level: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_level` wire field."""
    min_happiness: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_happiness` wire field."""
    min_beauty: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_beauty` wire field."""
    min_affection: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_affection` wire field."""
    near_special_rock: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `near_special_rock` wire field."""
    needs_multiplayer: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `needs_multiplayer` wire field."""
    needs_overworld_rain: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `needs_overworld_rain` wire field."""
    relative_physical_stats: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `relative_physical_stats` wire field."""
    time_of_day: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `time_of_day` wire field."""
    turn_upside_down: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `turn_upside_down` wire field."""
    min_move_count: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_move_count` wire field."""
    min_steps: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_steps` wire field."""
    min_damage_taken: int | None | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `min_damage_taken` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "allowed_natures",
                "condition_expression",
                "evolved_pokemon_form",
                "held_item",
                "item",
                "known_move",
                "known_move_type",
                "location",
                "party_species",
                "party_type",
                "region",
                "required_pokemon_form",
                "trade_species",
                "trigger",
                "used_move",
                "version_group",
            ],
        )
        return value

    @field_validator("min_level")
    @classmethod
    def _validate_min_level(cls, value):
        if value is not None:
            validate_range("min_level", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("min_happiness")
    @classmethod
    def _validate_min_happiness(cls, value):
        if value is not None:
            validate_range("min_happiness", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("min_beauty")
    @classmethod
    def _validate_min_beauty(cls, value):
        if value is not None:
            validate_range("min_beauty", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("min_affection")
    @classmethod
    def _validate_min_affection(cls, value):
        if value is not None:
            validate_range("min_affection", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("relative_physical_stats")
    @classmethod
    def _validate_relative_physical_stats(cls, value):
        if value is not None:
            validate_range("relative_physical_stats", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("time_of_day")
    @classmethod
    def _validate_time_of_day(cls, value):
        validate_length("time_of_day", value, max=10)
        return value

    @field_validator("min_move_count")
    @classmethod
    def _validate_min_move_count(cls, value):
        if value is not None:
            validate_range("min_move_count", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("min_steps")
    @classmethod
    def _validate_min_steps(cls, value):
        if value is not None:
            validate_range("min_steps", value, min=-2147483648, max=2147483647)
        return value

    @field_validator("min_damage_taken")
    @classmethod
    def _validate_min_damage_taken(cls, value):
        if value is not None:
            validate_range("min_damage_taken", value, min=-2147483648, max=2147483647)
        return value
