# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from sdk.client import NOT_GIVEN, NotGiven
from sdk.types.shared import (
    EvolutionChainSummary,
    ItemSummary,
    LanguageSummary,
    PokemonSpeciesSummary,
    VersionGroupSummary,
)

from ..validation import validate_length, validate_required, validate_uri

if TYPE_CHECKING:
    from sdk.types.evolution_part002 import PokemonEvolution


class EvolutionChainDetail(BaseModel):
    """Typed representation of the `EvolutionChainDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    baby_trigger_item: ItemSummary
    """Required object value serialized in the `baby_trigger_item` wire field."""
    chain: EvolutionChainLink
    """Required API value serialized in the `chain` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["baby_trigger_item", "chain", "id"])
        return value


class EvolutionChainLink(BaseModel):
    """Typed representation of the `EvolutionChainLink` API schema."""

    is_baby: bool
    """Required `boolean` value serialized in the `is_baby` wire field."""
    species: PokemonSpeciesSummary
    """Required object value serialized in the `species` wire field."""
    evolution_details: list[PokemonEvolution]
    """Required array value serialized in the `evolution_details` wire field."""
    evolves_to: list[dict[str, Any]]
    """Required array value serialized in the `evolves_to` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["evolution_details", "evolves_to", "is_baby", "species"])
        return value


class EvolutionConditionExpression(BaseModel):
    """Typed representation of the `EvolutionConditionExpression` API schema."""

    expression: str
    """Evaluatable RPN condition expression using evolution variables (e.g. 'EC 100 % 0 ==')"""
    percentage_chance: float | None
    """Percentage chance of evolution under this condition (0-100)"""
    variables: list[EvolutionVariableSummary]
    """Evolution variables referenced in the expression"""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["expression", "percentage_chance", "variables"])
        return value


class EvolutionTriggerDetail(BaseModel):
    """Typed representation of the `EvolutionTriggerDetail` API schema."""

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    names: list[EvolutionTriggerName]
    """Required array value serialized in the `names` wire field."""
    pokemon_species: list[PokemonSpeciesSummary]
    """Required array value serialized in the `pokemon_species` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["id", "name", "names", "pokemon_species"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class EvolutionTriggerName(BaseModel):
    """Typed representation of the `EvolutionTriggerName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class EvolutionTriggerSummary(BaseModel):
    """Typed representation of the `EvolutionTriggerSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class EvolutionVariableDescription(BaseModel):
    """Typed representation of the `EvolutionVariableDescription` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""
    description: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `description` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language"])
        return value

    @field_validator("description")
    @classmethod
    def _validate_description(cls, value):
        validate_length("description", value, max=2000)
        return value


class EvolutionVariableDetail(BaseModel):
    """Typed representation of the `EvolutionVariableDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    symbol: str
    """Required `string` value serialized in the `symbol` wire field."""
    version_group: VersionGroupSummary
    """Required object value serialized in the `version_group` wire field."""
    names: list[EvolutionVariableName]
    """Required array value serialized in the `names` wire field."""
    descriptions: list[EvolutionVariableDescription]
    """Required array value serialized in the `descriptions` wire field."""
    data_type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `data_type` wire field."""
    source: str | NotGiven = NOT_GIVEN
    """Where the value comes from: 'pokemon' for data stored on the Pokemon (e.g. EC, PID), 'player-input' for an action taken by the player while evolving (e.g. SPIN_DIR, SPIN_SEC)"""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["descriptions", "id", "name", "names", "symbol", "version_group"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("symbol")
    @classmethod
    def _validate_symbol(cls, value):
        validate_length("symbol", value, max=10)
        return value

    @field_validator("data_type")
    @classmethod
    def _validate_data_type(cls, value):
        validate_length("data_type", value, max=20)
        return value

    @field_validator("source")
    @classmethod
    def _validate_source(cls, value):
        validate_length("source", value, max=20)
        return value


class EvolutionVariableName(BaseModel):
    """Typed representation of the `EvolutionVariableName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class EvolutionVariableSummary(BaseModel):
    """Typed representation of the `EvolutionVariableSummary` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    url: str
    """Required `uri`-formatted value serialized in the `url` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["name", "url"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("url")
    @classmethod
    def _validate_url(cls, value):
        validate_uri("url", value)
        return value


class PaginatedEvolutionChainSummaryList(BaseModel):
    """Typed representation of the `PaginatedEvolutionChainSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[EvolutionChainSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedEvolutionTriggerSummaryList(BaseModel):
    """Typed representation of the `PaginatedEvolutionTriggerSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[EvolutionTriggerSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PaginatedEvolutionVariableSummaryList(BaseModel):
    """Typed representation of the `PaginatedEvolutionVariableSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[EvolutionVariableSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value
