# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from sdk.client import NOT_GIVEN, NotGiven
from sdk.types.pokemon_characteristic import CharacteristicSummary
from sdk.types.pokemon_move import MoveStatChange
from sdk.types.shared import ItemSummary, LanguageSummary, MoveDamageClassSummary, NatureSummary

from ..validation import validate_length, validate_range, validate_required


class StatAffectingMoves(BaseModel):
    """Typed representation of the `StatAffectingMoves` API schema."""

    increase: list[MoveStatChange]
    """Required array value serialized in the `increase` wire field."""
    decrease: list[MoveStatChange]
    """Required array value serialized in the `decrease` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["decrease", "increase"])
        return value


class StatAffectingNatures(BaseModel):
    """Typed representation of the `StatAffectingNatures` API schema."""

    increase: list[NatureSummary]
    """Required array value serialized in the `increase` wire field."""
    decrease: list[NatureSummary]
    """Required array value serialized in the `decrease` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["decrease", "increase"])
        return value


class StatDetail(BaseModel):
    """Typed representation of the `StatDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    game_index: int
    """Required `integer` value serialized in the `game_index` wire field."""
    affecting_moves: StatAffectingMoves
    """Required API value serialized in the `affecting_moves` wire field."""
    affecting_natures: StatAffectingNatures
    """Required API value serialized in the `affecting_natures` wire field."""
    affecting_items: list[ItemSummary]
    """Required array value serialized in the `affecting_items` wire field."""
    characteristics: list[CharacteristicSummary]
    """Required array value serialized in the `characteristics` wire field."""
    move_damage_class: MoveDamageClassSummary
    """Required object value serialized in the `move_damage_class` wire field."""
    names: list[StatName]
    """Required array value serialized in the `names` wire field."""
    is_battle_only: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_battle_only` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "affecting_items",
                "affecting_moves",
                "affecting_natures",
                "characteristics",
                "game_index",
                "id",
                "move_damage_class",
                "name",
                "names",
            ],
        )
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("game_index")
    @classmethod
    def _validate_game_index(cls, value):
        validate_range("game_index", value, min=-2147483648, max=2147483647)
        return value


class StatName(BaseModel):
    """Typed representation of the `StatName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value
