# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from sdk.client import NOT_GIVEN, NotGiven
from sdk.types.shared import LanguageSummary

from ..validation import validate_length, validate_required, validate_uri


class LanguageDetail(BaseModel):
    """Typed representation of the `LanguageDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: int
    """Required `integer` value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    iso639: str
    """Required `string` value serialized in the `iso639` wire field."""
    iso3166: str
    """Required `string` value serialized in the `iso3166` wire field."""
    names: list[LanguageName]
    """Required array value serialized in the `names` wire field."""
    official: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `official` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["id", "iso3166", "iso639", "name", "names"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value

    @field_validator("iso639")
    @classmethod
    def _validate_iso639(cls, value):
        validate_length("iso639", value, max=10)
        return value

    @field_validator("iso3166")
    @classmethod
    def _validate_iso3166(cls, value):
        validate_length("iso3166", value, max=2)
        return value


class LanguageName(BaseModel):
    """Typed representation of the `LanguageName` API schema."""

    name: str
    """Required `string` value serialized in the `name` wire field."""
    language: LanguageSummary
    """Required object value serialized in the `language` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["language", "name"])
        return value

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value):
        validate_length("name", value, max=200)
        return value


class PaginatedLanguageSummaryList(BaseModel):
    """Typed representation of the `PaginatedLanguageSummaryList` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    count: int
    """
    Required `integer` value serialized in the `count` wire field.

    @example 123
    """
    results: list[LanguageSummary]
    """Required array value serialized in the `results` wire field."""
    next: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `next` wire field.

    @example "http://api.example.org/accounts/?offset=400&limit=100"
    """
    previous: str | None | NotGiven = NOT_GIVEN
    """
    Optional `uri`-formatted value serialized in the `previous` wire field.

    @example "http://api.example.org/accounts/?offset=200&limit=100"
    """

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["count", "results"])
        return value

    @field_validator("next")
    @classmethod
    def _validate_next(cls, value):
        if value is not None:
            validate_uri("next", value)
        return value

    @field_validator("previous")
    @classmethod
    def _validate_previous(cls, value):
        if value is not None:
            validate_uri("previous", value)
        return value


class PokeapiMetaResponse(BaseModel):
    """Typed representation of the `PokeapiMetaResponse` API schema."""

    deploy_date: str | None
    """Required `string` value serialized in the `deploy_date` wire field."""
    hash: str | None
    """Required `string` value serialized in the `hash` wire field."""
    tag: str | None
    """Required `string` value serialized in the `tag` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["deploy_date", "hash", "tag"])
        return value
