# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from ..client import ClientConfig, LoggingConfig
from .berries import _BerriesNamespace
from .contests import _ContestsNamespace
from .encounters import _EncountersNamespace
from .evolution import _EvolutionNamespace
from .games import _GamesNamespace
from .items import _ItemsNamespace
from .location import _LocationNamespace
from .machines import _MachinesNamespace
from .moves import _MovesNamespace
from .pokemon import _PokemonNamespace
from .utility import _UtilityNamespace


class PokAPI:
    def __init__(self, config: ClientConfig) -> None:
        self._config = config
        self.utility = _UtilityNamespace(config)
        self.pokemon = _PokemonNamespace(config)
        self.berries = _BerriesNamespace(config)
        self.contests = _ContestsNamespace(config)
        self.encounters = _EncountersNamespace(config)
        self.evolution = _EvolutionNamespace(config)
        self.games = _GamesNamespace(config)
        self.items = _ItemsNamespace(config)
        self.location = _LocationNamespace(config)
        self.machines = _MachinesNamespace(config)
        self.moves = _MovesNamespace(config)

    def set_logging_config(
        self, config: LoggingConfig | None = None, **fields: Any
    ) -> LoggingConfig:
        """Turn SDK logging on and configure it.

        Logging is OFF by default — this SDK reports nothing until you call this
        (or construct the client with logging enabled). Reports go to the endpoint
        this build was generated with, or to the endpoint you pass; with neither,
        nothing is sent. Pass enabled=False to turn logging back off.
        """
        if self._config.logging is None:
            self._config.logging = LoggingConfig()
        current = self._config.logging
        if config is not None:
            for key, value in vars(config).items():
                if key != "enabled":
                    setattr(current, key, value)
        current.enabled = True
        for key, value in fields.items():
            if not hasattr(current, key):
                raise TypeError(f"LoggingConfig has no field {key!r}")
            setattr(current, key, value)
        return current


__all__ = ["PokAPI"]
