# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.location import (
    location_area_list,
    location_area_list_pages,
    location_area_list_pages_sync,
    location_area_list_paginated,
    location_area_list_paginated_sync,
    location_area_list_sync,
    location_area_retrieve,
    location_area_retrieve_sync,
    location_list,
    location_list_pages,
    location_list_pages_sync,
    location_list_paginated,
    location_list_paginated_sync,
    location_list_sync,
    location_retrieve,
    location_retrieve_sync,
    pal_park_area_list,
    pal_park_area_list_pages,
    pal_park_area_list_pages_sync,
    pal_park_area_list_paginated,
    pal_park_area_list_paginated_sync,
    pal_park_area_list_sync,
    pal_park_area_retrieve,
    pal_park_area_retrieve_sync,
    region_list,
    region_list_pages,
    region_list_pages_sync,
    region_list_paginated,
    region_list_paginated_sync,
    region_list_sync,
    region_retrieve,
    region_retrieve_sync,
)


class _LocationNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list = partial(location_list, config)
        self.list.__doc__ = location_list.__doc__
        self.list_sync = partial(location_list_sync, config)
        self.list_sync.__doc__ = location_list_sync.__doc__
        self.list_paginated = partial(location_list_paginated, config)
        self.list_paginated.__doc__ = location_list_paginated.__doc__
        self.list_pages = partial(location_list_pages, config)
        self.list_pages.__doc__ = location_list_pages.__doc__
        self.list_paginated_sync = partial(location_list_paginated_sync, config)
        self.list_paginated_sync.__doc__ = location_list_paginated_sync.__doc__
        self.list_pages_sync = partial(location_list_pages_sync, config)
        self.list_pages_sync.__doc__ = location_list_pages_sync.__doc__
        self.retrieve = partial(location_retrieve, config)
        self.retrieve.__doc__ = location_retrieve.__doc__
        self.retrieve_sync = partial(location_retrieve_sync, config)
        self.retrieve_sync.__doc__ = location_retrieve_sync.__doc__
        self.area_list = partial(location_area_list, config)
        self.area_list.__doc__ = location_area_list.__doc__
        self.area_list_sync = partial(location_area_list_sync, config)
        self.area_list_sync.__doc__ = location_area_list_sync.__doc__
        self.area_list_paginated = partial(location_area_list_paginated, config)
        self.area_list_paginated.__doc__ = location_area_list_paginated.__doc__
        self.area_list_pages = partial(location_area_list_pages, config)
        self.area_list_pages.__doc__ = location_area_list_pages.__doc__
        self.area_list_paginated_sync = partial(location_area_list_paginated_sync, config)
        self.area_list_paginated_sync.__doc__ = location_area_list_paginated_sync.__doc__
        self.area_list_pages_sync = partial(location_area_list_pages_sync, config)
        self.area_list_pages_sync.__doc__ = location_area_list_pages_sync.__doc__
        self.area_retrieve = partial(location_area_retrieve, config)
        self.area_retrieve.__doc__ = location_area_retrieve.__doc__
        self.area_retrieve_sync = partial(location_area_retrieve_sync, config)
        self.area_retrieve_sync.__doc__ = location_area_retrieve_sync.__doc__
        self.pal_park_area_list = partial(pal_park_area_list, config)
        self.pal_park_area_list.__doc__ = pal_park_area_list.__doc__
        self.pal_park_area_list_sync = partial(pal_park_area_list_sync, config)
        self.pal_park_area_list_sync.__doc__ = pal_park_area_list_sync.__doc__
        self.pal_park_area_list_paginated = partial(pal_park_area_list_paginated, config)
        self.pal_park_area_list_paginated.__doc__ = pal_park_area_list_paginated.__doc__
        self.pal_park_area_list_pages = partial(pal_park_area_list_pages, config)
        self.pal_park_area_list_pages.__doc__ = pal_park_area_list_pages.__doc__
        self.pal_park_area_list_paginated_sync = partial(pal_park_area_list_paginated_sync, config)
        self.pal_park_area_list_paginated_sync.__doc__ = pal_park_area_list_paginated_sync.__doc__
        self.pal_park_area_list_pages_sync = partial(pal_park_area_list_pages_sync, config)
        self.pal_park_area_list_pages_sync.__doc__ = pal_park_area_list_pages_sync.__doc__
        self.pal_park_area_retrieve = partial(pal_park_area_retrieve, config)
        self.pal_park_area_retrieve.__doc__ = pal_park_area_retrieve.__doc__
        self.pal_park_area_retrieve_sync = partial(pal_park_area_retrieve_sync, config)
        self.pal_park_area_retrieve_sync.__doc__ = pal_park_area_retrieve_sync.__doc__
        self.region_list = partial(region_list, config)
        self.region_list.__doc__ = region_list.__doc__
        self.region_list_sync = partial(region_list_sync, config)
        self.region_list_sync.__doc__ = region_list_sync.__doc__
        self.region_list_paginated = partial(region_list_paginated, config)
        self.region_list_paginated.__doc__ = region_list_paginated.__doc__
        self.region_list_pages = partial(region_list_pages, config)
        self.region_list_pages.__doc__ = region_list_pages.__doc__
        self.region_list_paginated_sync = partial(region_list_paginated_sync, config)
        self.region_list_paginated_sync.__doc__ = region_list_paginated_sync.__doc__
        self.region_list_pages_sync = partial(region_list_pages_sync, config)
        self.region_list_pages_sync.__doc__ = region_list_pages_sync.__doc__
        self.region_retrieve = partial(region_retrieve, config)
        self.region_retrieve.__doc__ = region_retrieve.__doc__
        self.region_retrieve_sync = partial(region_retrieve_sync, config)
        self.region_retrieve_sync.__doc__ = region_retrieve_sync.__doc__
