# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.pokemon import (
    ability_list,
    ability_list_pages,
    ability_list_pages_sync,
    ability_list_paginated,
    ability_list_paginated_sync,
    ability_list_sync,
    ability_retrieve,
    ability_retrieve_sync,
    characteristic_list,
    characteristic_list_pages,
    characteristic_list_pages_sync,
    characteristic_list_paginated,
    characteristic_list_paginated_sync,
    characteristic_list_sync,
    characteristic_retrieve,
    characteristic_retrieve_sync,
    egg_group_list,
    egg_group_list_pages,
    egg_group_list_pages_sync,
    egg_group_list_paginated,
    egg_group_list_paginated_sync,
    egg_group_list_sync,
    egg_group_retrieve,
    egg_group_retrieve_sync,
    gender_list,
    gender_list_pages,
    gender_list_pages_sync,
    gender_list_paginated,
    gender_list_paginated_sync,
    gender_list_sync,
    gender_retrieve,
    gender_retrieve_sync,
    growth_rate_list,
    growth_rate_list_pages,
    growth_rate_list_pages_sync,
    growth_rate_list_paginated,
    growth_rate_list_paginated_sync,
    growth_rate_list_sync,
    growth_rate_retrieve,
    growth_rate_retrieve_sync,
    move_damage_class_list,
    move_damage_class_list_pages,
    move_damage_class_list_pages_sync,
    move_damage_class_list_paginated,
    move_damage_class_list_paginated_sync,
    move_damage_class_list_sync,
    move_damage_class_retrieve,
    move_damage_class_retrieve_sync,
    nature_list,
    nature_list_pages,
    nature_list_pages_sync,
    nature_list_paginated,
    nature_list_paginated_sync,
    nature_list_sync,
    nature_retrieve,
    nature_retrieve_sync,
    pokeathlon_stat_list,
    pokeathlon_stat_list_pages,
    pokeathlon_stat_list_pages_sync,
    pokeathlon_stat_list_paginated,
    pokeathlon_stat_list_paginated_sync,
    pokeathlon_stat_list_sync,
    pokeathlon_stat_retrieve,
    pokeathlon_stat_retrieve_sync,
    pokemon_color_list,
    pokemon_color_list_pages,
    pokemon_color_list_pages_sync,
    pokemon_color_list_paginated,
    pokemon_color_list_paginated_sync,
    pokemon_color_list_sync,
    pokemon_color_retrieve,
    pokemon_color_retrieve_sync,
    pokemon_form_list,
    pokemon_form_list_pages,
    pokemon_form_list_pages_sync,
    pokemon_form_list_paginated,
    pokemon_form_list_paginated_sync,
    pokemon_form_list_sync,
    pokemon_form_retrieve,
    pokemon_form_retrieve_sync,
    pokemon_habitat_list,
    pokemon_habitat_list_pages,
    pokemon_habitat_list_pages_sync,
    pokemon_habitat_list_paginated,
    pokemon_habitat_list_paginated_sync,
    pokemon_habitat_list_sync,
    pokemon_habitat_retrieve,
    pokemon_habitat_retrieve_sync,
    pokemon_list,
    pokemon_list_pages,
    pokemon_list_pages_sync,
    pokemon_list_paginated,
    pokemon_list_paginated_sync,
    pokemon_list_sync,
    pokemon_retrieve,
    pokemon_retrieve_sync,
    pokemon_shape_list,
    pokemon_shape_list_pages,
    pokemon_shape_list_pages_sync,
    pokemon_shape_list_paginated,
    pokemon_shape_list_paginated_sync,
    pokemon_shape_list_sync,
    pokemon_shape_retrieve,
    pokemon_shape_retrieve_sync,
    pokemon_species_list,
    pokemon_species_list_pages,
    pokemon_species_list_pages_sync,
    pokemon_species_list_paginated,
    pokemon_species_list_paginated_sync,
    pokemon_species_list_sync,
    pokemon_species_retrieve,
    pokemon_species_retrieve_sync,
    stat_list,
    stat_list_pages,
    stat_list_pages_sync,
    stat_list_paginated,
    stat_list_paginated_sync,
    stat_list_sync,
    stat_retrieve,
    stat_retrieve_sync,
    type_list,
    type_list_pages,
    type_list_pages_sync,
    type_list_paginated,
    type_list_paginated_sync,
    type_list_sync,
    type_retrieve,
    type_retrieve_sync,
)


class _PokemonNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.ability_list = partial(ability_list, config)
        self.ability_list.__doc__ = ability_list.__doc__
        self.ability_list_sync = partial(ability_list_sync, config)
        self.ability_list_sync.__doc__ = ability_list_sync.__doc__
        self.ability_list_paginated = partial(ability_list_paginated, config)
        self.ability_list_paginated.__doc__ = ability_list_paginated.__doc__
        self.ability_list_pages = partial(ability_list_pages, config)
        self.ability_list_pages.__doc__ = ability_list_pages.__doc__
        self.ability_list_paginated_sync = partial(ability_list_paginated_sync, config)
        self.ability_list_paginated_sync.__doc__ = ability_list_paginated_sync.__doc__
        self.ability_list_pages_sync = partial(ability_list_pages_sync, config)
        self.ability_list_pages_sync.__doc__ = ability_list_pages_sync.__doc__
        self.ability_retrieve = partial(ability_retrieve, config)
        self.ability_retrieve.__doc__ = ability_retrieve.__doc__
        self.ability_retrieve_sync = partial(ability_retrieve_sync, config)
        self.ability_retrieve_sync.__doc__ = ability_retrieve_sync.__doc__
        self.characteristic_list = partial(characteristic_list, config)
        self.characteristic_list.__doc__ = characteristic_list.__doc__
        self.characteristic_list_sync = partial(characteristic_list_sync, config)
        self.characteristic_list_sync.__doc__ = characteristic_list_sync.__doc__
        self.characteristic_list_paginated = partial(characteristic_list_paginated, config)
        self.characteristic_list_paginated.__doc__ = characteristic_list_paginated.__doc__
        self.characteristic_list_pages = partial(characteristic_list_pages, config)
        self.characteristic_list_pages.__doc__ = characteristic_list_pages.__doc__
        self.characteristic_list_paginated_sync = partial(
            characteristic_list_paginated_sync, config
        )
        self.characteristic_list_paginated_sync.__doc__ = characteristic_list_paginated_sync.__doc__
        self.characteristic_list_pages_sync = partial(characteristic_list_pages_sync, config)
        self.characteristic_list_pages_sync.__doc__ = characteristic_list_pages_sync.__doc__
        self.characteristic_retrieve = partial(characteristic_retrieve, config)
        self.characteristic_retrieve.__doc__ = characteristic_retrieve.__doc__
        self.characteristic_retrieve_sync = partial(characteristic_retrieve_sync, config)
        self.characteristic_retrieve_sync.__doc__ = characteristic_retrieve_sync.__doc__
        self.egg_group_list = partial(egg_group_list, config)
        self.egg_group_list.__doc__ = egg_group_list.__doc__
        self.egg_group_list_sync = partial(egg_group_list_sync, config)
        self.egg_group_list_sync.__doc__ = egg_group_list_sync.__doc__
        self.egg_group_list_paginated = partial(egg_group_list_paginated, config)
        self.egg_group_list_paginated.__doc__ = egg_group_list_paginated.__doc__
        self.egg_group_list_pages = partial(egg_group_list_pages, config)
        self.egg_group_list_pages.__doc__ = egg_group_list_pages.__doc__
        self.egg_group_list_paginated_sync = partial(egg_group_list_paginated_sync, config)
        self.egg_group_list_paginated_sync.__doc__ = egg_group_list_paginated_sync.__doc__
        self.egg_group_list_pages_sync = partial(egg_group_list_pages_sync, config)
        self.egg_group_list_pages_sync.__doc__ = egg_group_list_pages_sync.__doc__
        self.egg_group_retrieve = partial(egg_group_retrieve, config)
        self.egg_group_retrieve.__doc__ = egg_group_retrieve.__doc__
        self.egg_group_retrieve_sync = partial(egg_group_retrieve_sync, config)
        self.egg_group_retrieve_sync.__doc__ = egg_group_retrieve_sync.__doc__
        self.gender_list = partial(gender_list, config)
        self.gender_list.__doc__ = gender_list.__doc__
        self.gender_list_sync = partial(gender_list_sync, config)
        self.gender_list_sync.__doc__ = gender_list_sync.__doc__
        self.gender_list_paginated = partial(gender_list_paginated, config)
        self.gender_list_paginated.__doc__ = gender_list_paginated.__doc__
        self.gender_list_pages = partial(gender_list_pages, config)
        self.gender_list_pages.__doc__ = gender_list_pages.__doc__
        self.gender_list_paginated_sync = partial(gender_list_paginated_sync, config)
        self.gender_list_paginated_sync.__doc__ = gender_list_paginated_sync.__doc__
        self.gender_list_pages_sync = partial(gender_list_pages_sync, config)
        self.gender_list_pages_sync.__doc__ = gender_list_pages_sync.__doc__
        self.gender_retrieve = partial(gender_retrieve, config)
        self.gender_retrieve.__doc__ = gender_retrieve.__doc__
        self.gender_retrieve_sync = partial(gender_retrieve_sync, config)
        self.gender_retrieve_sync.__doc__ = gender_retrieve_sync.__doc__
        self.growth_rate_list = partial(growth_rate_list, config)
        self.growth_rate_list.__doc__ = growth_rate_list.__doc__
        self.growth_rate_list_sync = partial(growth_rate_list_sync, config)
        self.growth_rate_list_sync.__doc__ = growth_rate_list_sync.__doc__
        self.growth_rate_list_paginated = partial(growth_rate_list_paginated, config)
        self.growth_rate_list_paginated.__doc__ = growth_rate_list_paginated.__doc__
        self.growth_rate_list_pages = partial(growth_rate_list_pages, config)
        self.growth_rate_list_pages.__doc__ = growth_rate_list_pages.__doc__
        self.growth_rate_list_paginated_sync = partial(growth_rate_list_paginated_sync, config)
        self.growth_rate_list_paginated_sync.__doc__ = growth_rate_list_paginated_sync.__doc__
        self.growth_rate_list_pages_sync = partial(growth_rate_list_pages_sync, config)
        self.growth_rate_list_pages_sync.__doc__ = growth_rate_list_pages_sync.__doc__
        self.growth_rate_retrieve = partial(growth_rate_retrieve, config)
        self.growth_rate_retrieve.__doc__ = growth_rate_retrieve.__doc__
        self.growth_rate_retrieve_sync = partial(growth_rate_retrieve_sync, config)
        self.growth_rate_retrieve_sync.__doc__ = growth_rate_retrieve_sync.__doc__
        self.move_damage_class_list = partial(move_damage_class_list, config)
        self.move_damage_class_list.__doc__ = move_damage_class_list.__doc__
        self.move_damage_class_list_sync = partial(move_damage_class_list_sync, config)
        self.move_damage_class_list_sync.__doc__ = move_damage_class_list_sync.__doc__
        self.move_damage_class_list_paginated = partial(move_damage_class_list_paginated, config)
        self.move_damage_class_list_paginated.__doc__ = move_damage_class_list_paginated.__doc__
        self.move_damage_class_list_pages = partial(move_damage_class_list_pages, config)
        self.move_damage_class_list_pages.__doc__ = move_damage_class_list_pages.__doc__
        self.move_damage_class_list_paginated_sync = partial(
            move_damage_class_list_paginated_sync, config
        )
        self.move_damage_class_list_paginated_sync.__doc__ = (
            move_damage_class_list_paginated_sync.__doc__
        )
        self.move_damage_class_list_pages_sync = partial(move_damage_class_list_pages_sync, config)
        self.move_damage_class_list_pages_sync.__doc__ = move_damage_class_list_pages_sync.__doc__
        self.move_damage_class_retrieve = partial(move_damage_class_retrieve, config)
        self.move_damage_class_retrieve.__doc__ = move_damage_class_retrieve.__doc__
        self.move_damage_class_retrieve_sync = partial(move_damage_class_retrieve_sync, config)
        self.move_damage_class_retrieve_sync.__doc__ = move_damage_class_retrieve_sync.__doc__
        self.nature_list = partial(nature_list, config)
        self.nature_list.__doc__ = nature_list.__doc__
        self.nature_list_sync = partial(nature_list_sync, config)
        self.nature_list_sync.__doc__ = nature_list_sync.__doc__
        self.nature_list_paginated = partial(nature_list_paginated, config)
        self.nature_list_paginated.__doc__ = nature_list_paginated.__doc__
        self.nature_list_pages = partial(nature_list_pages, config)
        self.nature_list_pages.__doc__ = nature_list_pages.__doc__
        self.nature_list_paginated_sync = partial(nature_list_paginated_sync, config)
        self.nature_list_paginated_sync.__doc__ = nature_list_paginated_sync.__doc__
        self.nature_list_pages_sync = partial(nature_list_pages_sync, config)
        self.nature_list_pages_sync.__doc__ = nature_list_pages_sync.__doc__
        self.nature_retrieve = partial(nature_retrieve, config)
        self.nature_retrieve.__doc__ = nature_retrieve.__doc__
        self.nature_retrieve_sync = partial(nature_retrieve_sync, config)
        self.nature_retrieve_sync.__doc__ = nature_retrieve_sync.__doc__
        self.list = partial(pokemon_list, config)
        self.list.__doc__ = pokemon_list.__doc__
        self.list_sync = partial(pokemon_list_sync, config)
        self.list_sync.__doc__ = pokemon_list_sync.__doc__
        self.list_paginated = partial(pokemon_list_paginated, config)
        self.list_paginated.__doc__ = pokemon_list_paginated.__doc__
        self.list_pages = partial(pokemon_list_pages, config)
        self.list_pages.__doc__ = pokemon_list_pages.__doc__
        self.list_paginated_sync = partial(pokemon_list_paginated_sync, config)
        self.list_paginated_sync.__doc__ = pokemon_list_paginated_sync.__doc__
        self.list_pages_sync = partial(pokemon_list_pages_sync, config)
        self.list_pages_sync.__doc__ = pokemon_list_pages_sync.__doc__
        self.retrieve = partial(pokemon_retrieve, config)
        self.retrieve.__doc__ = pokemon_retrieve.__doc__
        self.retrieve_sync = partial(pokemon_retrieve_sync, config)
        self.retrieve_sync.__doc__ = pokemon_retrieve_sync.__doc__
        self.color_list = partial(pokemon_color_list, config)
        self.color_list.__doc__ = pokemon_color_list.__doc__
        self.color_list_sync = partial(pokemon_color_list_sync, config)
        self.color_list_sync.__doc__ = pokemon_color_list_sync.__doc__
        self.color_list_paginated = partial(pokemon_color_list_paginated, config)
        self.color_list_paginated.__doc__ = pokemon_color_list_paginated.__doc__
        self.color_list_pages = partial(pokemon_color_list_pages, config)
        self.color_list_pages.__doc__ = pokemon_color_list_pages.__doc__
        self.color_list_paginated_sync = partial(pokemon_color_list_paginated_sync, config)
        self.color_list_paginated_sync.__doc__ = pokemon_color_list_paginated_sync.__doc__
        self.color_list_pages_sync = partial(pokemon_color_list_pages_sync, config)
        self.color_list_pages_sync.__doc__ = pokemon_color_list_pages_sync.__doc__
        self.color_retrieve = partial(pokemon_color_retrieve, config)
        self.color_retrieve.__doc__ = pokemon_color_retrieve.__doc__
        self.color_retrieve_sync = partial(pokemon_color_retrieve_sync, config)
        self.color_retrieve_sync.__doc__ = pokemon_color_retrieve_sync.__doc__
        self.form_list = partial(pokemon_form_list, config)
        self.form_list.__doc__ = pokemon_form_list.__doc__
        self.form_list_sync = partial(pokemon_form_list_sync, config)
        self.form_list_sync.__doc__ = pokemon_form_list_sync.__doc__
        self.form_list_paginated = partial(pokemon_form_list_paginated, config)
        self.form_list_paginated.__doc__ = pokemon_form_list_paginated.__doc__
        self.form_list_pages = partial(pokemon_form_list_pages, config)
        self.form_list_pages.__doc__ = pokemon_form_list_pages.__doc__
        self.form_list_paginated_sync = partial(pokemon_form_list_paginated_sync, config)
        self.form_list_paginated_sync.__doc__ = pokemon_form_list_paginated_sync.__doc__
        self.form_list_pages_sync = partial(pokemon_form_list_pages_sync, config)
        self.form_list_pages_sync.__doc__ = pokemon_form_list_pages_sync.__doc__
        self.form_retrieve = partial(pokemon_form_retrieve, config)
        self.form_retrieve.__doc__ = pokemon_form_retrieve.__doc__
        self.form_retrieve_sync = partial(pokemon_form_retrieve_sync, config)
        self.form_retrieve_sync.__doc__ = pokemon_form_retrieve_sync.__doc__
        self.habitat_list = partial(pokemon_habitat_list, config)
        self.habitat_list.__doc__ = pokemon_habitat_list.__doc__
        self.habitat_list_sync = partial(pokemon_habitat_list_sync, config)
        self.habitat_list_sync.__doc__ = pokemon_habitat_list_sync.__doc__
        self.habitat_list_paginated = partial(pokemon_habitat_list_paginated, config)
        self.habitat_list_paginated.__doc__ = pokemon_habitat_list_paginated.__doc__
        self.habitat_list_pages = partial(pokemon_habitat_list_pages, config)
        self.habitat_list_pages.__doc__ = pokemon_habitat_list_pages.__doc__
        self.habitat_list_paginated_sync = partial(pokemon_habitat_list_paginated_sync, config)
        self.habitat_list_paginated_sync.__doc__ = pokemon_habitat_list_paginated_sync.__doc__
        self.habitat_list_pages_sync = partial(pokemon_habitat_list_pages_sync, config)
        self.habitat_list_pages_sync.__doc__ = pokemon_habitat_list_pages_sync.__doc__
        self.habitat_retrieve = partial(pokemon_habitat_retrieve, config)
        self.habitat_retrieve.__doc__ = pokemon_habitat_retrieve.__doc__
        self.habitat_retrieve_sync = partial(pokemon_habitat_retrieve_sync, config)
        self.habitat_retrieve_sync.__doc__ = pokemon_habitat_retrieve_sync.__doc__
        self.shape_list = partial(pokemon_shape_list, config)
        self.shape_list.__doc__ = pokemon_shape_list.__doc__
        self.shape_list_sync = partial(pokemon_shape_list_sync, config)
        self.shape_list_sync.__doc__ = pokemon_shape_list_sync.__doc__
        self.shape_list_paginated = partial(pokemon_shape_list_paginated, config)
        self.shape_list_paginated.__doc__ = pokemon_shape_list_paginated.__doc__
        self.shape_list_pages = partial(pokemon_shape_list_pages, config)
        self.shape_list_pages.__doc__ = pokemon_shape_list_pages.__doc__
        self.shape_list_paginated_sync = partial(pokemon_shape_list_paginated_sync, config)
        self.shape_list_paginated_sync.__doc__ = pokemon_shape_list_paginated_sync.__doc__
        self.shape_list_pages_sync = partial(pokemon_shape_list_pages_sync, config)
        self.shape_list_pages_sync.__doc__ = pokemon_shape_list_pages_sync.__doc__
        self.shape_retrieve = partial(pokemon_shape_retrieve, config)
        self.shape_retrieve.__doc__ = pokemon_shape_retrieve.__doc__
        self.shape_retrieve_sync = partial(pokemon_shape_retrieve_sync, config)
        self.shape_retrieve_sync.__doc__ = pokemon_shape_retrieve_sync.__doc__
        self.species_list = partial(pokemon_species_list, config)
        self.species_list.__doc__ = pokemon_species_list.__doc__
        self.species_list_sync = partial(pokemon_species_list_sync, config)
        self.species_list_sync.__doc__ = pokemon_species_list_sync.__doc__
        self.species_list_paginated = partial(pokemon_species_list_paginated, config)
        self.species_list_paginated.__doc__ = pokemon_species_list_paginated.__doc__
        self.species_list_pages = partial(pokemon_species_list_pages, config)
        self.species_list_pages.__doc__ = pokemon_species_list_pages.__doc__
        self.species_list_paginated_sync = partial(pokemon_species_list_paginated_sync, config)
        self.species_list_paginated_sync.__doc__ = pokemon_species_list_paginated_sync.__doc__
        self.species_list_pages_sync = partial(pokemon_species_list_pages_sync, config)
        self.species_list_pages_sync.__doc__ = pokemon_species_list_pages_sync.__doc__
        self.species_retrieve = partial(pokemon_species_retrieve, config)
        self.species_retrieve.__doc__ = pokemon_species_retrieve.__doc__
        self.species_retrieve_sync = partial(pokemon_species_retrieve_sync, config)
        self.species_retrieve_sync.__doc__ = pokemon_species_retrieve_sync.__doc__
        self.pokeathlon_stat_list = partial(pokeathlon_stat_list, config)
        self.pokeathlon_stat_list.__doc__ = pokeathlon_stat_list.__doc__
        self.pokeathlon_stat_list_sync = partial(pokeathlon_stat_list_sync, config)
        self.pokeathlon_stat_list_sync.__doc__ = pokeathlon_stat_list_sync.__doc__
        self.pokeathlon_stat_list_paginated = partial(pokeathlon_stat_list_paginated, config)
        self.pokeathlon_stat_list_paginated.__doc__ = pokeathlon_stat_list_paginated.__doc__
        self.pokeathlon_stat_list_pages = partial(pokeathlon_stat_list_pages, config)
        self.pokeathlon_stat_list_pages.__doc__ = pokeathlon_stat_list_pages.__doc__
        self.pokeathlon_stat_list_paginated_sync = partial(
            pokeathlon_stat_list_paginated_sync, config
        )
        self.pokeathlon_stat_list_paginated_sync.__doc__ = (
            pokeathlon_stat_list_paginated_sync.__doc__
        )
        self.pokeathlon_stat_list_pages_sync = partial(pokeathlon_stat_list_pages_sync, config)
        self.pokeathlon_stat_list_pages_sync.__doc__ = pokeathlon_stat_list_pages_sync.__doc__
        self.pokeathlon_stat_retrieve = partial(pokeathlon_stat_retrieve, config)
        self.pokeathlon_stat_retrieve.__doc__ = pokeathlon_stat_retrieve.__doc__
        self.pokeathlon_stat_retrieve_sync = partial(pokeathlon_stat_retrieve_sync, config)
        self.pokeathlon_stat_retrieve_sync.__doc__ = pokeathlon_stat_retrieve_sync.__doc__
        self.stat_list = partial(stat_list, config)
        self.stat_list.__doc__ = stat_list.__doc__
        self.stat_list_sync = partial(stat_list_sync, config)
        self.stat_list_sync.__doc__ = stat_list_sync.__doc__
        self.stat_list_paginated = partial(stat_list_paginated, config)
        self.stat_list_paginated.__doc__ = stat_list_paginated.__doc__
        self.stat_list_pages = partial(stat_list_pages, config)
        self.stat_list_pages.__doc__ = stat_list_pages.__doc__
        self.stat_list_paginated_sync = partial(stat_list_paginated_sync, config)
        self.stat_list_paginated_sync.__doc__ = stat_list_paginated_sync.__doc__
        self.stat_list_pages_sync = partial(stat_list_pages_sync, config)
        self.stat_list_pages_sync.__doc__ = stat_list_pages_sync.__doc__
        self.stat_retrieve = partial(stat_retrieve, config)
        self.stat_retrieve.__doc__ = stat_retrieve.__doc__
        self.stat_retrieve_sync = partial(stat_retrieve_sync, config)
        self.stat_retrieve_sync.__doc__ = stat_retrieve_sync.__doc__
        self.type_list = partial(type_list, config)
        self.type_list.__doc__ = type_list.__doc__
        self.type_list_sync = partial(type_list_sync, config)
        self.type_list_sync.__doc__ = type_list_sync.__doc__
        self.type_list_paginated = partial(type_list_paginated, config)
        self.type_list_paginated.__doc__ = type_list_paginated.__doc__
        self.type_list_pages = partial(type_list_pages, config)
        self.type_list_pages.__doc__ = type_list_pages.__doc__
        self.type_list_paginated_sync = partial(type_list_paginated_sync, config)
        self.type_list_paginated_sync.__doc__ = type_list_paginated_sync.__doc__
        self.type_list_pages_sync = partial(type_list_pages_sync, config)
        self.type_list_pages_sync.__doc__ = type_list_pages_sync.__doc__
        self.type_retrieve = partial(type_retrieve, config)
        self.type_retrieve.__doc__ = type_retrieve.__doc__
        self.type_retrieve_sync = partial(type_retrieve_sync, config)
        self.type_retrieve_sync.__doc__ = type_retrieve_sync.__doc__
