# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.utility import (
    language_list,
    language_list_pages,
    language_list_pages_sync,
    language_list_paginated,
    language_list_paginated_sync,
    language_list_sync,
    language_retrieve,
    language_retrieve_sync,
    meta_retrieve,
    meta_retrieve_sync,
)


class _UtilityNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.meta_retrieve = partial(meta_retrieve, config)
        self.meta_retrieve.__doc__ = meta_retrieve.__doc__
        self.meta_retrieve_sync = partial(meta_retrieve_sync, config)
        self.meta_retrieve_sync.__doc__ = meta_retrieve_sync.__doc__
        self.language_list = partial(language_list, config)
        self.language_list.__doc__ = language_list.__doc__
        self.language_list_sync = partial(language_list_sync, config)
        self.language_list_sync.__doc__ = language_list_sync.__doc__
        self.language_list_paginated = partial(language_list_paginated, config)
        self.language_list_paginated.__doc__ = language_list_paginated.__doc__
        self.language_list_pages = partial(language_list_pages, config)
        self.language_list_pages.__doc__ = language_list_pages.__doc__
        self.language_list_paginated_sync = partial(language_list_paginated_sync, config)
        self.language_list_paginated_sync.__doc__ = language_list_paginated_sync.__doc__
        self.language_list_pages_sync = partial(language_list_pages_sync, config)
        self.language_list_pages_sync.__doc__ = language_list_pages_sync.__doc__
        self.language_retrieve = partial(language_retrieve, config)
        self.language_retrieve.__doc__ = language_retrieve.__doc__
        self.language_retrieve_sync = partial(language_retrieve_sync, config)
        self.language_retrieve_sync.__doc__ = language_retrieve_sync.__doc__
