# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    MoveBattleStyleDetail,
    MoveBattleStyleSummary,
    MoveMetaCategoryDetail,
    MoveMetaCategorySummary,
    PaginatedMoveBattleStyleSummaryList,
    PaginatedMoveMetaCategorySummaryList,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def move_battle_style_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedMoveBattleStyleSummaryList:
    """Lists move battle styles, which describe how moves are used in the Battle Palace.
    Use `limit` and `offset` to control the results page, and use `q` to filter style
    names case-insensitively in local deployments.

    Styles of moves when used in the Battle Palace. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_(Generation_III)
    ) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/move-battle-style/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="move_battle_style_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedMoveBattleStyleSummaryList"),
        PaginatedMoveBattleStyleSummaryList,
    )


def move_battle_style_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedMoveBattleStyleSummaryList:
    """Lists move battle styles, which describe how moves are used in the Battle Palace.
    Use `limit` and `offset` to control the results page, and use `q` to filter style
    names case-insensitively in local deployments.

    Styles of moves when used in the Battle Palace. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_(Generation_III)
    ) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/move-battle-style/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="move_battle_style_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedMoveBattleStyleSummaryList"),
        PaginatedMoveBattleStyleSummaryList,
    )


async def move_battle_style_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[MoveBattleStyleSummary]:
    """Lists move battle styles, which describe how moves are used in the Battle Palace.
    Use `limit` and `offset` to control the results page, and use `q` to filter style
    names case-insensitively in local deployments.

    Styles of moves when used in the Battle Palace. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_(Generation_III)
    ) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await move_battle_style_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveBattleStyleSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="move_battle_style_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveBattleStyleSummaryList"),
            PaginatedMoveBattleStyleSummaryList,
        )


async def move_battle_style_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedMoveBattleStyleSummaryList, MoveBattleStyleSummary]]:
    _page = await move_battle_style_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveBattleStyleSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="move_battle_style_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveBattleStyleSummaryList"),
            PaginatedMoveBattleStyleSummaryList,
        )


def move_battle_style_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[MoveBattleStyleSummary]:
    """Lists move battle styles, which describe how moves are used in the Battle Palace.
    Use `limit` and `offset` to control the results page, and use `q` to filter style
    names case-insensitively in local deployments.

    Styles of moves when used in the Battle Palace. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_(Generation_III)
    ) for greater detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = move_battle_style_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveBattleStyleSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="move_battle_style_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveBattleStyleSummaryList"),
            PaginatedMoveBattleStyleSummaryList,
        )


def move_battle_style_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedMoveBattleStyleSummaryList, MoveBattleStyleSummary]]:
    _page = move_battle_style_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveBattleStyleSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="move_battle_style_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveBattleStyleSummaryList"),
            PaginatedMoveBattleStyleSummaryList,
        )


async def move_battle_style_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> MoveBattleStyleDetail:
    """Retrieves the Battle Palace move battle style identified by `id`. Use this operation
    to look up a style and its localized names.

    Styles of moves when used in the Battle Palace. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_(Generation_III)
    ) for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/move-battle-style/{encode_path_segment(id)}/",
        operation_id="move_battle_style_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "MoveBattleStyleDetail"), MoveBattleStyleDetail
    )


def move_battle_style_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> MoveBattleStyleDetail:
    """Retrieves the Battle Palace move battle style identified by `id`. Use this operation
    to look up a style and its localized names.

    Styles of moves when used in the Battle Palace. See
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_(Generation_III)
    ) for greater detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/move-battle-style/{encode_path_segment(id)}/",
        operation_id="move_battle_style_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "MoveBattleStyleDetail"), MoveBattleStyleDetail
    )


async def move_category_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedMoveMetaCategorySummaryList:
    """Lists move categories, which loosely group move effects. Use `q` to filter by name
    with a case-insensitive query; this filter is available locally but not at
    pokeapi.co.

    Very general categories that loosely group move effects.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/move-category/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="move_category_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedMoveMetaCategorySummaryList"),
        PaginatedMoveMetaCategorySummaryList,
    )


def move_category_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedMoveMetaCategorySummaryList:
    """Lists move categories, which loosely group move effects. Use `q` to filter by name
    with a case-insensitive query; this filter is available locally but not at
    pokeapi.co.

    Very general categories that loosely group move effects.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/move-category/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="move_category_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedMoveMetaCategorySummaryList"),
        PaginatedMoveMetaCategorySummaryList,
    )


async def move_category_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[MoveMetaCategorySummary]:
    """Lists move categories, which loosely group move effects. Use `q` to filter by name
    with a case-insensitive query; this filter is available locally but not at
    pokeapi.co.

    Very general categories that loosely group move effects.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await move_category_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveMetaCategorySummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="move_category_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveMetaCategorySummaryList"),
            PaginatedMoveMetaCategorySummaryList,
        )


async def move_category_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedMoveMetaCategorySummaryList, MoveMetaCategorySummary]]:
    _page = await move_category_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveMetaCategorySummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="move_category_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveMetaCategorySummaryList"),
            PaginatedMoveMetaCategorySummaryList,
        )


def move_category_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[MoveMetaCategorySummary]:
    """Lists move categories, which loosely group move effects. Use `q` to filter by name
    with a case-insensitive query; this filter is available locally but not at
    pokeapi.co.

    Very general categories that loosely group move effects.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = move_category_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveMetaCategorySummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="move_category_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveMetaCategorySummaryList"),
            PaginatedMoveMetaCategorySummaryList,
        )


def move_category_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedMoveMetaCategorySummaryList, MoveMetaCategorySummary]]:
    _page = move_category_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[MoveMetaCategorySummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="move_category_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedMoveMetaCategorySummaryList"),
            PaginatedMoveMetaCategorySummaryList,
        )


async def move_category_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> MoveMetaCategoryDetail:
    """Retrieves a move category, which loosely groups move effects. Use the category
    identifier to look up its descriptions and associated moves.

    Very general categories that loosely group move effects.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/move-category/{encode_path_segment(id)}/",
        operation_id="move_category_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "MoveMetaCategoryDetail"), MoveMetaCategoryDetail
    )


def move_category_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> MoveMetaCategoryDetail:
    """Retrieves a move category, which loosely groups move effects. Use the category
    identifier to look up its descriptions and associated moves.

    Very general categories that loosely group move effects.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/move-category/{encode_path_segment(id)}/",
        operation_id="move_category_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "MoveMetaCategoryDetail"), MoveMetaCategoryDetail
    )


__all__ = [
    "move_battle_style_list",
    "move_battle_style_list_pages",
    "move_battle_style_list_pages_sync",
    "move_battle_style_list_paginated",
    "move_battle_style_list_paginated_sync",
    "move_battle_style_list_sync",
    "move_battle_style_retrieve",
    "move_battle_style_retrieve_sync",
    "move_category_list",
    "move_category_list_pages",
    "move_category_list_pages_sync",
    "move_category_list_paginated",
    "move_category_list_paginated_sync",
    "move_category_list_sync",
    "move_category_retrieve",
    "move_category_retrieve_sync",
]
