# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    GenerationDetail,
    GenerationSummary,
    PaginatedGenerationSummaryList,
    PaginatedPokedexSummaryList,
    PokedexDetail,
    PokedexSummary,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def generation_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedGenerationSummaryList:
    """Lists generations, which group Pokémon games by the Pokémon, moves, abilities, and
    types they include. Use `limit` and `offset` to control the result page, or search
    generation names with `q`, which is available only on local deployments.

    A generation is a grouping of the Pokémon games that separates them based on the
    Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and
    Types that did not exist in the previous generation are released.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/generation/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="generation_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedGenerationSummaryList"),
        PaginatedGenerationSummaryList,
    )


def generation_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedGenerationSummaryList:
    """Lists generations, which group Pokémon games by the Pokémon, moves, abilities, and
    types they include. Use `limit` and `offset` to control the result page, or search
    generation names with `q`, which is available only on local deployments.

    A generation is a grouping of the Pokémon games that separates them based on the
    Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and
    Types that did not exist in the previous generation are released.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/generation/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="generation_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedGenerationSummaryList"),
        PaginatedGenerationSummaryList,
    )


async def generation_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[GenerationSummary]:
    """Lists generations, which group Pokémon games by the Pokémon, moves, abilities, and
    types they include. Use `limit` and `offset` to control the result page, or search
    generation names with `q`, which is available only on local deployments.

    A generation is a grouping of the Pokémon games that separates them based on the
    Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and
    Types that did not exist in the previous generation are released.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await generation_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[GenerationSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="generation_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedGenerationSummaryList"),
            PaginatedGenerationSummaryList,
        )


async def generation_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedGenerationSummaryList, GenerationSummary]]:
    _page = await generation_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[GenerationSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="generation_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedGenerationSummaryList"),
            PaginatedGenerationSummaryList,
        )


def generation_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[GenerationSummary]:
    """Lists generations, which group Pokémon games by the Pokémon, moves, abilities, and
    types they include. Use `limit` and `offset` to control the result page, or search
    generation names with `q`, which is available only on local deployments.

    A generation is a grouping of the Pokémon games that separates them based on the
    Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and
    Types that did not exist in the previous generation are released.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = generation_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[GenerationSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="generation_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedGenerationSummaryList"),
            PaginatedGenerationSummaryList,
        )


def generation_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedGenerationSummaryList, GenerationSummary]]:
    _page = generation_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[GenerationSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="generation_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedGenerationSummaryList"),
            PaginatedGenerationSummaryList,
        )


async def generation_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> GenerationDetail:
    """Retrieves a generation and its associated Pokémon data. Use the `id` path parameter
    to select a generation and view its region, Pokémon species, moves, abilities,
    types, and version groups.

    A generation is a grouping of the Pokémon games that separates them based on the
    Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and
    Types that did not exist in the previous generation are released.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/generation/{encode_path_segment(id)}/",
        operation_id="generation_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GenerationDetail"), GenerationDetail
    )


def generation_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> GenerationDetail:
    """Retrieves a generation and its associated Pokémon data. Use the `id` path parameter
    to select a generation and view its region, Pokémon species, moves, abilities,
    types, and version groups.

    A generation is a grouping of the Pokémon games that separates them based on the
    Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and
    Types that did not exist in the previous generation are released.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/generation/{encode_path_segment(id)}/",
        operation_id="generation_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "GenerationDetail"), GenerationDetail
    )


async def pokedex_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokedexSummaryList:
    """Lists Pokédex records that catalog Pokémon entries for regions or other defined
    groups. Use `limit` and `offset` to paginate the results, or use `q` to search
    Pokédex names when running the API locally.

    A Pokédex is a handheld electronic encyclopedia device; one which is capable of
    recording and retaining information of the various Pokémon in a given region with
    the exception of the national dex and some smaller dexes related to portions of a
    region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/pokedex/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokedex_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokedexSummaryList"),
        PaginatedPokedexSummaryList,
    )


def pokedex_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedPokedexSummaryList:
    """Lists Pokédex records that catalog Pokémon entries for regions or other defined
    groups. Use `limit` and `offset` to paginate the results, or use `q` to search
    Pokédex names when running the API locally.

    A Pokédex is a handheld electronic encyclopedia device; one which is capable of
    recording and retaining information of the various Pokémon in a given region with
    the exception of the national dex and some smaller dexes related to portions of a
    region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/pokedex/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="pokedex_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedPokedexSummaryList"),
        PaginatedPokedexSummaryList,
    )


async def pokedex_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[PokedexSummary]:
    """Lists Pokédex records that catalog Pokémon entries for regions or other defined
    groups. Use `limit` and `offset` to paginate the results, or use `q` to search
    Pokédex names when running the API locally.

    A Pokédex is a handheld electronic encyclopedia device; one which is capable of
    recording and retaining information of the various Pokémon in a given region with
    the exception of the national dex and some smaller dexes related to portions of a
    region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await pokedex_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[PokedexSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokedex_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokedexSummaryList"),
            PaginatedPokedexSummaryList,
        )


async def pokedex_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedPokedexSummaryList, PokedexSummary]]:
    _page = await pokedex_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[PokedexSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="pokedex_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokedexSummaryList"),
            PaginatedPokedexSummaryList,
        )


def pokedex_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[PokedexSummary]:
    """Lists Pokédex records that catalog Pokémon entries for regions or other defined
    groups. Use `limit` and `offset` to paginate the results, or use `q` to search
    Pokédex names when running the API locally.

    A Pokédex is a handheld electronic encyclopedia device; one which is capable of
    recording and retaining information of the various Pokémon in a given region with
    the exception of the national dex and some smaller dexes related to portions of a
    region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = pokedex_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[PokedexSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokedex_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokedexSummaryList"),
            PaginatedPokedexSummaryList,
        )


def pokedex_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedPokedexSummaryList, PokedexSummary]]:
    _page = pokedex_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[PokedexSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="pokedex_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedPokedexSummaryList"),
            PaginatedPokedexSummaryList,
        )


async def pokedex_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokedexDetail:
    """Retrieves a Pokédex record and its catalog of Pokémon species. Use the Pokédex
    identifier to look up its region, version groups, and numbered Pokémon entries.

    A Pokédex is a handheld electronic encyclopedia device; one which is capable of
    recording and retaining information of the various Pokémon in a given region with
    the exception of the national dex and some smaller dexes related to portions of a
    region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/pokedex/{encode_path_segment(id)}/",
        operation_id="pokedex_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokedexDetail"), PokedexDetail
    )


def pokedex_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> PokedexDetail:
    """Retrieves a Pokédex record and its catalog of Pokémon species. Use the Pokédex
    identifier to look up its region, version groups, and numbered Pokémon entries.

    A Pokédex is a handheld electronic encyclopedia device; one which is capable of
    recording and retaining information of the various Pokémon in a given region with
    the exception of the national dex and some smaller dexes related to portions of a
    region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/pokedex/{encode_path_segment(id)}/",
        operation_id="pokedex_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PokedexDetail"), PokedexDetail
    )


__all__ = [
    "generation_list",
    "generation_list_pages",
    "generation_list_pages_sync",
    "generation_list_paginated",
    "generation_list_paginated_sync",
    "generation_list_sync",
    "generation_retrieve",
    "generation_retrieve_sync",
    "pokedex_list",
    "pokedex_list_pages",
    "pokedex_list_pages_sync",
    "pokedex_list_paginated",
    "pokedex_list_paginated_sync",
    "pokedex_list_sync",
    "pokedex_retrieve",
    "pokedex_retrieve_sync",
]
