# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import octri_pokeapi_unofficial_demo_sdk.types as _response_types
from octri_pokeapi_unofficial_demo_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from octri_pokeapi_unofficial_demo_sdk.types import (
    PaginatedVersionGroupSummaryList,
    PaginatedVersionSummaryList,
    VersionDetail,
    VersionGroupDetail,
    VersionGroupSummary,
    VersionSummary,
)
from octri_pokeapi_unofficial_demo_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def version_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedVersionSummaryList:
    """Lists game versions such as Red, Blue, and Yellow. Use `limit` and `offset` to
    control the results, or use `q` to search version names case-insensitively; `q` is
    available only on the local API.

    Versions of the games, e.g., Red, Blue or Yellow.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/version/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="version_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedVersionSummaryList"),
        PaginatedVersionSummaryList,
    )


def version_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedVersionSummaryList:
    """Lists game versions such as Red, Blue, and Yellow. Use `limit` and `offset` to
    control the results, or use `q` to search version names case-insensitively; `q` is
    available only on the local API.

    Versions of the games, e.g., Red, Blue or Yellow.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/version/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="version_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedVersionSummaryList"),
        PaginatedVersionSummaryList,
    )


async def version_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[VersionSummary]:
    """Lists game versions such as Red, Blue, and Yellow. Use `limit` and `offset` to
    control the results, or use `q` to search version names case-insensitively; `q` is
    available only on the local API.

    Versions of the games, e.g., Red, Blue or Yellow.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await version_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[VersionSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="version_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionSummaryList"),
            PaginatedVersionSummaryList,
        )


async def version_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedVersionSummaryList, VersionSummary]]:
    _page = await version_list(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[VersionSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="version_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionSummaryList"),
            PaginatedVersionSummaryList,
        )


def version_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[VersionSummary]:
    """Lists game versions such as Red, Blue, and Yellow. Use `limit` and `offset` to
    control the results, or use `q` to search version names case-insensitively; `q` is
    available only on the local API.

    Versions of the games, e.g., Red, Blue or Yellow.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = version_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[VersionSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="version_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionSummaryList"),
            PaginatedVersionSummaryList,
        )


def version_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedVersionSummaryList, VersionSummary]]:
    _page = version_list_sync(_client_config, limit, offset, q, request_options=request_options)
    while True:
        _items: list[VersionSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="version_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionSummaryList"),
            PaginatedVersionSummaryList,
        )


async def version_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> VersionDetail:
    """Retrieves a game version, such as Red, Blue, or Yellow. Use the `id` path parameter
    to identify the version, then inspect its localized names and associated version
    group.

    Versions of the games, e.g., Red, Blue or Yellow.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/version/{encode_path_segment(id)}/",
        operation_id="version_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "VersionDetail"), VersionDetail
    )


def version_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> VersionDetail:
    """Retrieves a game version, such as Red, Blue, or Yellow. Use the `id` path parameter
    to identify the version, then inspect its localized names and associated version
    group.

    Versions of the games, e.g., Red, Blue or Yellow.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/version/{encode_path_segment(id)}/",
        operation_id="version_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "VersionDetail"), VersionDetail
    )


async def version_group_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedVersionGroupSummaryList:
    """Lists version groups that categorize highly similar game versions. Use `limit` and
    `offset` to control the results, or use `q` to search version group names
    case-insensitively; `q` is available only on the local API.

    Version groups categorize highly similar versions of the games.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/version-group/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="version_group_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedVersionGroupSummaryList"),
        PaginatedVersionGroupSummaryList,
    )


def version_group_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedVersionGroupSummaryList:
    """Lists version groups that categorize highly similar game versions. Use `limit` and
    `offset` to control the results, or use `q` to search version group names
    case-insensitively; `q` is available only on the local API.

    Version groups categorize highly similar versions of the games.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/version-group/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="version_group_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedVersionGroupSummaryList"),
        PaginatedVersionGroupSummaryList,
    )


async def version_group_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[VersionGroupSummary]:
    """Lists version groups that categorize highly similar game versions. Use `limit` and
    `offset` to control the results, or use `q` to search version group names
    case-insensitively; `q` is available only on the local API.

    Version groups categorize highly similar versions of the games.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await version_group_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[VersionGroupSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="version_group_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionGroupSummaryList"),
            PaginatedVersionGroupSummaryList,
        )


async def version_group_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedVersionGroupSummaryList, VersionGroupSummary]]:
    _page = await version_group_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[VersionGroupSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="version_group_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionGroupSummaryList"),
            PaginatedVersionGroupSummaryList,
        )


def version_group_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[VersionGroupSummary]:
    """Lists version groups that categorize highly similar game versions. Use `limit` and
    `offset` to control the results, or use `q` to search version group names
    case-insensitively; `q` is available only on the local API.

    Version groups categorize highly similar versions of the games.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = version_group_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[VersionGroupSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="version_group_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionGroupSummaryList"),
            PaginatedVersionGroupSummaryList,
        )


def version_group_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedVersionGroupSummaryList, VersionGroupSummary]]:
    _page = version_group_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[VersionGroupSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="version_group_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedVersionGroupSummaryList"),
            PaginatedVersionGroupSummaryList,
        )


async def version_group_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> VersionGroupDetail:
    """Retrieves a version group by its identifier. Version groups categorize highly
    similar game versions, and the response includes the associated generation,
    move-learn methods, Pokédexes, regions, and versions.

    Version groups categorize highly similar versions of the games.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/version-group/{encode_path_segment(id)}/",
        operation_id="version_group_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "VersionGroupDetail"), VersionGroupDetail
    )


def version_group_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> VersionGroupDetail:
    """Retrieves a version group by its identifier. Version groups categorize highly
    similar game versions, and the response includes the associated generation,
    move-learn methods, Pokédexes, regions, and versions.

    Version groups categorize highly similar versions of the games.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/version-group/{encode_path_segment(id)}/",
        operation_id="version_group_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "VersionGroupDetail"), VersionGroupDetail
    )


__all__ = [
    "version_group_list",
    "version_group_list_pages",
    "version_group_list_pages_sync",
    "version_group_list_paginated",
    "version_group_list_paginated_sync",
    "version_group_list_sync",
    "version_group_retrieve",
    "version_group_retrieve_sync",
    "version_list",
    "version_list_pages",
    "version_list_pages_sync",
    "version_list_paginated",
    "version_list_paginated_sync",
    "version_list_sync",
    "version_retrieve",
    "version_retrieve_sync",
]
