# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator
from typing import Any

from pydantic import TypeAdapter

import sdk.types as _response_types
from sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    SdkPage,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from sdk.types import (
    ContestEffectDetail,
    ContestEffectSummary,
    ContestTypeDetail,
    ContestTypeSummary,
    PaginatedContestEffectSummaryList,
    PaginatedContestTypeSummaryList,
)
from sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def contest_type_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedContestTypeSummaryList:
    """Lists contest types used to categorize how judges weigh a Pokémon's condition in
    contests. Use `limit` and `offset` to control the result page, or filter by name
    with the locally available, case-insensitive `q` query.

    Contest types are categories judges used to weigh a Pokémon's condition in Pokémon
    contests. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/contest-type/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="contest_type_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedContestTypeSummaryList"),
        PaginatedContestTypeSummaryList,
    )


def contest_type_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedContestTypeSummaryList:
    """Lists contest types used to categorize how judges weigh a Pokémon's condition in
    contests. Use `limit` and `offset` to control the result page, or filter by name
    with the locally available, case-insensitive `q` query.

    Contest types are categories judges used to weigh a Pokémon's condition in Pokémon
    contests. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/contest-type/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="contest_type_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedContestTypeSummaryList"),
        PaginatedContestTypeSummaryList,
    )


async def contest_type_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[ContestTypeSummary]:
    """Lists contest types used to categorize how judges weigh a Pokémon's condition in
    contests. Use `limit` and `offset` to control the result page, or filter by name
    with the locally available, case-insensitive `q` query.

    Contest types are categories judges used to weigh a Pokémon's condition in Pokémon
    contests. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await contest_type_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestTypeSummary] = _page.results if isinstance(_page.results, list) else []
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="contest_type_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestTypeSummaryList"),
            PaginatedContestTypeSummaryList,
        )


async def contest_type_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedContestTypeSummaryList, ContestTypeSummary]]:
    _page = await contest_type_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestTypeSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="contest_type_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestTypeSummaryList"),
            PaginatedContestTypeSummaryList,
        )


def contest_type_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[ContestTypeSummary]:
    """Lists contest types used to categorize how judges weigh a Pokémon's condition in
    contests. Use `limit` and `offset` to control the result page, or filter by name
    with the locally available, case-insensitive `q` query.

    Contest types are categories judges used to weigh a Pokémon's condition in Pokémon
    contests. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater
    detail.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = contest_type_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestTypeSummary] = _page.results if isinstance(_page.results, list) else []
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="contest_type_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestTypeSummaryList"),
            PaginatedContestTypeSummaryList,
        )


def contest_type_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedContestTypeSummaryList, ContestTypeSummary]]:
    _page = contest_type_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestTypeSummary] = _page.results if isinstance(_page.results, list) else []
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="contest_type_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestTypeSummaryList"),
            PaginatedContestTypeSummaryList,
        )


async def contest_type_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> ContestTypeDetail:
    """Retrieves a contest type used to categorize how judges weigh a Pokémon's condition
    in contests. Use the `id` path parameter to view its name, associated berry flavor,
    and localized names.

    Contest types are categories judges used to weigh a Pokémon's condition in Pokémon
    contests. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/contest-type/{encode_path_segment(id)}/",
        operation_id="contest_type_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ContestTypeDetail"), ContestTypeDetail
    )


def contest_type_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> ContestTypeDetail:
    """Retrieves a contest type used to categorize how judges weigh a Pokémon's condition
    in contests. Use the `id` path parameter to view its name, associated berry flavor,
    and localized names.

    Contest types are categories judges used to weigh a Pokémon's condition in Pokémon
    contests. Check out
    [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater
    detail.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/contest-type/{encode_path_segment(id)}/",
        operation_id="contest_type_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ContestTypeDetail"), ContestTypeDetail
    )


async def contest_effect_list(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedContestEffectSummaryList:
    """Lists effects that moves have when used in Pokémon contests. Use `limit` and
    `offset` to control the result page, or filter by name with the locally available,
    case-insensitive `q` query.

    Contest effects refer to the effects of moves when used in contests.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v2/contest-effect/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="contest_effect_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedContestEffectSummaryList"),
        PaginatedContestEffectSummaryList,
    )


def contest_effect_list_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PaginatedContestEffectSummaryList:
    """Lists effects that moves have when used in Pokémon contests. Use `limit` and
    `offset` to control the result page, or filter by name with the locally available,
    case-insensitive `q` query.

    Contest effects refer to the effects of moves when used in contests.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v2/contest-effect/",
        params=serialize_query(
            [
                ("limit", limit, "form", True),
                ("offset", offset, "form", True),
                ("q", q, "form", True),
            ]
        ),
        operation_id="contest_effect_list",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PaginatedContestEffectSummaryList"),
        PaginatedContestEffectSummaryList,
    )


async def contest_effect_list_paginated(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[ContestEffectSummary]:
    """Lists effects that moves have when used in Pokémon contests. Use `limit` and
    `offset` to control the result page, or filter by name with the locally available,
    case-insensitive `q` query.

    Contest effects refer to the effects of moves when used in contests.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = await contest_effect_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestEffectSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        for item in _items:
            yield item
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="contest_effect_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestEffectSummaryList"),
            PaginatedContestEffectSummaryList,
        )


async def contest_effect_list_pages(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AsyncIterator[SdkPage[PaginatedContestEffectSummaryList, ContestEffectSummary]]:
    _page = await contest_effect_list(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestEffectSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = await sdk_request(
            "GET",
            _next_url,
            operation_id="contest_effect_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestEffectSummaryList"),
            PaginatedContestEffectSummaryList,
        )


def contest_effect_list_paginated_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[ContestEffectSummary]:
    """Lists effects that moves have when used in Pokémon contests. Use `limit` and
    `offset` to control the result page, or filter by name with the locally available,
    case-insensitive `q` query.

    Contest effects refer to the effects of moves when used in contests.

    Args:
        limit: Number of results to return per page.
        offset: The initial index from which to return the results.
        q: > Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2)
            Case-insensitive query applied on the `name` property.
    """
    _page = contest_effect_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestEffectSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        yield from _items
        _next_url = _page.next
        if isinstance(_next_url, NotGiven) or not _next_url:
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="contest_effect_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestEffectSummaryList"),
            PaginatedContestEffectSummaryList,
        )


def contest_effect_list_pages_sync(
    _client_config: ClientConfig,
    limit: int | NotGiven = NOT_GIVEN,
    offset: int | NotGiven = NOT_GIVEN,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> Iterator[SdkPage[PaginatedContestEffectSummaryList, ContestEffectSummary]]:
    _page = contest_effect_list_sync(
        _client_config, limit, offset, q, request_options=request_options
    )
    while True:
        _items: list[ContestEffectSummary] = (
            _page.results if isinstance(_page.results, list) else []
        )
        _next_url = _page.next
        _has_more = not isinstance(_next_url, NotGiven) and bool(_next_url)
        yield SdkPage(data=_page, items=_items, has_more=_has_more)
        if not _has_more or not isinstance(_next_url, str):
            break
        _resp = sdk_request_sync(
            "GET",
            _next_url,
            operation_id="contest_effect_list",
            config=_client_config,
            request_options=request_options,
        )
        _page = _validate_pydantic_response(
            _validate_response_enums(_resp.data, "PaginatedContestEffectSummaryList"),
            PaginatedContestEffectSummaryList,
        )


async def contest_effect_retrieve(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> ContestEffectDetail:
    """Retrieves the effect of a move when used in a Pokémon contest. Use the `id` path
    parameter to view its appeal and jam values, effect entries, and localized flavor
    text.

    Contest effects refer to the effects of moves when used in contests.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v2/contest-effect/{encode_path_segment(id)}/",
        operation_id="contest_effect_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ContestEffectDetail"), ContestEffectDetail
    )


def contest_effect_retrieve_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> ContestEffectDetail:
    """Retrieves the effect of a move when used in a Pokémon contest. Use the `id` path
    parameter to view its appeal and jam values, effect entries, and localized flavor
    text.

    Contest effects refer to the effects of moves when used in contests.

    Args:
        id: This parameter can be a string or an integer.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v2/contest-effect/{encode_path_segment(id)}/",
        operation_id="contest_effect_retrieve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ContestEffectDetail"), ContestEffectDetail
    )


__all__ = [
    "contest_effect_list",
    "contest_effect_list_pages",
    "contest_effect_list_pages_sync",
    "contest_effect_list_paginated",
    "contest_effect_list_paginated_sync",
    "contest_effect_list_sync",
    "contest_effect_retrieve",
    "contest_effect_retrieve_sync",
    "contest_type_list",
    "contest_type_list_pages",
    "contest_type_list_pages_sync",
    "contest_type_list_paginated",
    "contest_type_list_paginated_sync",
    "contest_type_list_sync",
    "contest_type_retrieve",
    "contest_type_retrieve_sync",
]
